$folder = "public/images/products"
Rename-Item -Path (Join-Path $folder "1000HB.jpg") -NewName "1000-hb.jpg"
Rename-Item -Path (Join-Path $folder "1001HB.jpg") -NewName "1001-hb.jpg"
Rename-Item -Path (Join-Path $folder "1002HB.jpg") -NewName "1002-hb.jpg"
Rename-Item -Path (Join-Path $folder "1003HB.jpg") -NewName "1003-hb.jpg"
Rename-Item -Path (Join-Path $folder "1004HB.jpg") -NewName "1004-hb.jpg"
Rename-Item -Path (Join-Path $folder "1005HB.jpg") -NewName "1005-hb.jpg"
Rename-Item -Path (Join-Path $folder "101Alaphabet Express.jpg") -NewName "101-alaphabet-express.jpg"
Rename-Item -Path (Join-Path $folder "102Baby's First Blocks.jpg") -NewName "102-baby-s-first-blocks.jpg"
Rename-Item -Path (Join-Path $folder "103Baby Multi-sensory Blocks.jpg") -NewName "103-baby-multi-sensory-blocks.jpg"
Rename-Item -Path (Join-Path $folder "104Binoculars.jpg") -NewName "104-binoculars.jpg"
Rename-Item -Path (Join-Path $folder "105Blanket Funny Pizza.jpg") -NewName "105-blanket-funny-pizza.jpg"
Rename-Item -Path (Join-Path $folder "106Buddy the Cat Ride-on.jpg") -NewName "106-buddy-the-cat-ride-on.jpg"
Rename-Item -Path (Join-Path $folder "107Bug Viewer,Catcher, & Magnifier .jpg") -NewName "107-bug-viewer-catcher-and-magnifier.jpg"
Rename-Item -Path (Join-Path $folder "108Burger and Fries.jpg") -NewName "108-burger-and-fries.jpg"
Rename-Item -Path (Join-Path $folder "109Calico Cat Warmie.png") -NewName "109-calico-cat-warmie.png"
Rename-Item -Path (Join-Path $folder "110Carpenter Dress Up Set.webp") -NewName "110-carpenter-dress-up-set.webp"
Rename-Item -Path (Join-Path $folder "111Caterpillar Xylophone.jpg") -NewName "111-caterpillar-xylophone.jpg"
Rename-Item -Path (Join-Path $folder "112Clean Up Set.jpg") -NewName "112-clean-up-set.jpg"
Rename-Item -Path (Join-Path $folder "113Corn Popper.jpg") -NewName "113-corn-popper.jpg"
Rename-Item -Path (Join-Path $folder "114Crinkle Toy.jpg") -NewName "114-crinkle-toy.jpg"
Rename-Item -Path (Join-Path $folder "115Dig It Up - Volcano.jpeg") -NewName "115-dig-it-up-volcano.jpeg"
Rename-Item -Path (Join-Path $folder "116Dimple Digit.jpg") -NewName "116-dimple-digit.jpg"
Rename-Item -Path (Join-Path $folder "117Dishwashing Fun Set.jpg") -NewName "117-dishwashing-fun-set.jpg"
Rename-Item -Path (Join-Path $folder "118Easy Grasp Ball.jpg") -NewName "118-easy-grasp-ball.jpg"
Rename-Item -Path (Join-Path $folder "119Floor Piano Playmat.jpg") -NewName "119-floor-piano-playmat.jpg"
Rename-Item -Path (Join-Path $folder "120Golden Dog Warmies.png") -NewName "120-golden-dog-warmies.png"
Rename-Item -Path (Join-Path $folder "121Johnny Jungle Plane.jpeg") -NewName "121-johnny-jungle-plane.jpeg"
Rename-Item -Path (Join-Path $folder "122Jungle Maracas Egg Shakers.jpg") -NewName "122-jungle-maracas-egg-shakers.jpg"
Rename-Item -Path (Join-Path $folder "123Karaoke Microphone.jpg") -NewName "123-karaoke-microphone.jpg"
Rename-Item -Path (Join-Path $folder "124Kitchen Set.jpg") -NewName "124-kitchen-set.jpg"
Rename-Item -Path (Join-Path $folder "125Kittens.jpg") -NewName "125-kittens.jpg"
Rename-Item -Path (Join-Path $folder "126LiquiFly FizzRocket.png") -NewName "126-liquifly-fizzrocket.png"
Rename-Item -Path (Join-Path $folder "127Magnetic Tiles Toys.png") -NewName "127-magnetic-tiles-toys.png"
Rename-Item -Path (Join-Path $folder "128Makeup & Bag.jpg") -NewName "128-makeup-and-bag.jpg"
Rename-Item -Path (Join-Path $folder "129Make-up Brushes.jpg") -NewName "129-make-up-brushes.jpg"
Rename-Item -Path (Join-Path $folder "130Makeup - Essentials.jpg") -NewName "130-makeup-essentials.jpg"
Rename-Item -Path (Join-Path $folder "131Marble Run.jpg") -NewName "131-marble-run.jpg"
Rename-Item -Path (Join-Path $folder "132Marble Tracks Builder Set.jpg") -NewName "132-marble-tracks-builder-set.jpg"
Rename-Item -Path (Join-Path $folder "133Math Dice.jpg") -NewName "133-math-dice.jpg"
Rename-Item -Path (Join-Path $folder "134MegaBlocks.jpg") -NewName "134-mega-blocks.jpg"
Rename-Item -Path (Join-Path $folder "135Mr. Potato Head.jpg") -NewName "135-mr-potato-head.jpg"
Rename-Item -Path (Join-Path $folder "136Musical Toy.jpg") -NewName "136-musical-toy.jpg"
Rename-Item -Path (Join-Path $folder "137Music Parade Ride-On.png") -NewName "137-music-parade-ride-on.png"
Rename-Item -Path (Join-Path $folder "138My Toolbox.jpg") -NewName "138-my-toolbox.jpg"
Rename-Item -Path (Join-Path $folder "139Picnic Set.jpg") -NewName "139-picnic-set.jpg"
Rename-Item -Path (Join-Path $folder "140Play Tunnel.jpg") -NewName "140-play-tunnel.jpg"
Rename-Item -Path (Join-Path $folder "141Pop-its 100.jpg") -NewName "141-pop-its-100.jpg"
Rename-Item -Path (Join-Path $folder "142Pop its 1-100.jpg") -NewName "142-pop-its-1-100.jpg"
Rename-Item -Path (Join-Path $folder "143Pop-Its Fidgets.jpg") -NewName "143-pop-its-fidgets.jpg"
Rename-Item -Path (Join-Path $folder "144Pound-A-Ball Toy.jpg") -NewName "144-pound-a-ball-toy.jpg"
Rename-Item -Path (Join-Path $folder "145Princess Tent.png") -NewName "145-princess-tent.png"
Rename-Item -Path (Join-Path $folder "146Ring Spinners.jpg") -NewName "146-ring-spinners.jpg"
Rename-Item -Path (Join-Path $folder "147Rock n' Roller Piano.webp") -NewName "147-rock-n-roller-piano.webp"
Rename-Item -Path (Join-Path $folder "148Rocking Horse .jpg") -NewName "148-rocking-horse.jpg"
Rename-Item -Path (Join-Path $folder "149Rubber Ball.jpg") -NewName "149-rubber-ball.jpg"
Rename-Item -Path (Join-Path $folder "150Rubber Pop Up Toys.jpg") -NewName "150-rubber-pop-up-toys.jpg"
Rename-Item -Path (Join-Path $folder "151Rubik's Cube.jpg") -NewName "151-rubik-s-cube.jpg"
Rename-Item -Path (Join-Path $folder "152Sensory Strings - 6 pack.jpg") -NewName "152-sensory-strings-6-pack.jpg"
Rename-Item -Path (Join-Path $folder "153Sit ‘n Spin .png") -NewName "153-sit-n-spin.png"
Rename-Item -Path (Join-Path $folder "154Slide for Toddlers.jpg") -NewName "154-slide-for-toddlers.jpg"
Rename-Item -Path (Join-Path $folder "155Slinky.jpg") -NewName "155-slinky.jpg"
Rename-Item -Path (Join-Path $folder "156Snow Beauty.jpg") -NewName "156-snow-beauty.jpg"
Rename-Item -Path (Join-Path $folder "157Spa Kit.jpg") -NewName "157-spa-kit.jpg"
Rename-Item -Path (Join-Path $folder "158Spike the Hedgehog.jpg") -NewName "158-spike-the-hedgehog.jpg"
Rename-Item -Path (Join-Path $folder "159Stack and Count Cups.jpg") -NewName "159-stack-and-count-cups.jpg"
Rename-Item -Path (Join-Path $folder "160Stuffed Animal - Dog.jpg") -NewName "160-stuffed-animal-dog.jpg"
Rename-Item -Path (Join-Path $folder "161Stuffed Animal - Hamburger Bear.jpg") -NewName "161-stuffed-animal-hamburger-bear.jpg"
Rename-Item -Path (Join-Path $folder "162Stuffed Animal - Hedgehog.jpg") -NewName "162-stuffed-animal-hedgehog.jpg"
Rename-Item -Path (Join-Path $folder "163Stuffed Animal - Unicorn Cat.jpg") -NewName "163-stuffed-animal-unicorn-cat.jpg"
Rename-Item -Path (Join-Path $folder "164Super Heroes - Action Figures.jpg") -NewName "164-super-heroes-action-figures.jpg"
Rename-Item -Path (Join-Path $folder "165Tea Party Set.jpg") -NewName "165-tea-party-set.jpg"
Rename-Item -Path (Join-Path $folder "166Thinking Putty - Mixed Emotions.png") -NewName "166-thinking-putty-mixed-emotions.png"
Rename-Item -Path (Join-Path $folder "167Toddler Bike.webp") -NewName "167-toddler-bike.webp"
Rename-Item -Path (Join-Path $folder "168Transformable Spinner.jpg") -NewName "168-transformable-spinner.jpg"
Rename-Item -Path (Join-Path $folder "169Unicorn Tea Set.jpg") -NewName "169-unicorn-tea-set.jpg"
Rename-Item -Path (Join-Path $folder "170Warmie Bear.jpg") -NewName "170-voice-changer.jpg"
Rename-Item -Path (Join-Path $folder "171Whirl'n Go Ball Tower Kidoozie.jpg") -NewName "171-warmie-bear.jpg"
Rename-Item -Path (Join-Path $folder "172Voice Changer.jpg") -NewName "172-whirl-n-go-ball-tower-kidoozie.jpg"
Rename-Item -Path (Join-Path $folder "173Wood Blocks.jpg") -NewName "173-wood-blocks.jpg"
Rename-Item -Path (Join-Path $folder "174Wooden Bee Ride-on.jpg") -NewName "174-wooden-bee-ride-on.jpg"
Rename-Item -Path (Join-Path $folder "175Wooden Stacking Rings.jpg") -NewName "175-wooden-stacking-rings.jpg"
Rename-Item -Path (Join-Path $folder "176Yo yo.jpg") -NewName "176-yo-yo.jpg"
Rename-Item -Path (Join-Path $folder "177Black Boy Doll.webp") -NewName "177-black-boy-doll.webp"
Rename-Item -Path (Join-Path $folder "178Boy Doll.jpg") -NewName "178-boy-doll.jpg"
Rename-Item -Path (Join-Path $folder "179Doll Girl.jpg") -NewName "179-doll-girl.jpg"
Rename-Item -Path (Join-Path $folder "180Girl Plush Doll.jpg") -NewName "180-girl-plush-doll.jpg"
Rename-Item -Path (Join-Path $folder "181La Baby Hispanic.png") -NewName "181-la-baby-hispanic-doll.png"
Rename-Item -Path (Join-Path $folder "182Latino doll.jpg") -NewName "182-latino-baby-doll.jpg"
Rename-Item -Path (Join-Path $folder "183Soccer Doll.jpg") -NewName "183-soccer-doll.jpg"
Rename-Item -Path (Join-Path $folder "184Wee Baby Doll.jpeg") -NewName "184-wee-baby-doll.jpeg"
Rename-Item -Path (Join-Path $folder "185White Baby Doll.jpg") -NewName "185-white-baby-doll.jpg"
Rename-Item -Path (Join-Path $folder "186WildlifePhotographer.webp") -NewName "186-wildlife-photographer-doll.webp"
Rename-Item -Path (Join-Path $folder "187Doll Red Dress.jpg") -NewName "187-doll-red-dress.jpg"
Rename-Item -Path (Join-Path $folder "188Legos Chain Reaction.jpg") -NewName "188-legos-chain-reaction.jpg"
Rename-Item -Path (Join-Path $folder "189Legos Dino.jpg") -NewName "189-legos-dino.jpg"
Rename-Item -Path (Join-Path $folder "190Legos Flower.jpg") -NewName "190-legos-flower.jpg"
Rename-Item -Path (Join-Path $folder "191Legos Gearbots.jpg") -NewName "191-legos-gearbots.jpg"
Rename-Item -Path (Join-Path $folder "192Lego Set.jpg") -NewName "192-lego-set.jpg"
Rename-Item -Path (Join-Path $folder "193Lego Spiderman.jpg") -NewName "193-lego-spiderman.jpg"
Rename-Item -Path (Join-Path $folder "194Construction Trucks .jpg") -NewName "194-construction-trucks.jpg"
Rename-Item -Path (Join-Path $folder "195Emergency Vehicle Carrier.jpg") -NewName "195-emergency-vehicle-carrier.jpg"
Rename-Item -Path (Join-Path $folder "196Hot Wheels Track Builder.jpg") -NewName "196-hot-wheels-track-builder.jpg"
Rename-Item -Path (Join-Path $folder "197John Deere Trucks.jpg") -NewName "197-john-deere-trucks.jpg"
Rename-Item -Path (Join-Path $folder "198Magnetic Racer.png") -NewName "198-magnetic-racer.png"
Rename-Item -Path (Join-Path $folder "199Monster Trucks.jpg") -NewName "199-monster-trucks.jpg"
Rename-Item -Path (Join-Path $folder "2000CC Cookie Cake & Vanilla Frosting.jpeg") -NewName "2000-cc-cookie-cake-and-vanilla-frosting.jpeg"
Rename-Item -Path (Join-Path $folder "2001CC Cookie Cake Chocolate Frosting.jpeg") -NewName "2001-cc-cookie-cake-and-chocolate-frosting.jpeg"
Rename-Item -Path (Join-Path $folder "2002Chocolate Cake Chocolate Frosting.jpeg") -NewName "2002-chocolate-cake-chocolate-frosting.jpeg"
Rename-Item -Path (Join-Path $folder "2003Chocolate Cake Vanilla Frosting.jpeg") -NewName "2003-chocolate-cake-vanilla-frosting.jpeg"
Rename-Item -Path (Join-Path $folder "2004Chocolate Chip Cookie Cake.jpeg") -NewName "2004-chocolate-chip-cookie.jpeg"
Rename-Item -Path (Join-Path $folder "2005Cookies-Brownie.jpeg") -NewName "2005-cookies-browine.jpeg"
Rename-Item -Path (Join-Path $folder "2006Cookies-Chocolate Chip.jpeg") -NewName "2006-cookies-chocolate-chip.jpeg"
Rename-Item -Path (Join-Path $folder "2007Cookies Sugar.jpeg") -NewName "2007-cookies-sugar.jpeg"
Rename-Item -Path (Join-Path $folder "2008Dairy Free Cake Vanilla Frosting.jpeg") -NewName "2008-dairy-free-cake-vanilla-frosting.jpeg"
Rename-Item -Path (Join-Path $folder "2009Marble Cake & Chocolate Frosting.jpeg") -NewName "2009-marble-cake-chocolate-frosting.jpeg"
Rename-Item -Path (Join-Path $folder "200AmazingMachines Big Bulldozers .jpg") -NewName "200-neighbor-s-garage.jpg"
Rename-Item -Path (Join-Path $folder "200Neighbors Garage.jpg") -NewName "200-amazing-machines-big-bulldozers.jpg"
Rename-Item -Path (Join-Path $folder "2010Marble Cake & Vanilla Frosting.jpeg") -NewName "2010-marble-cake-vanilla-frosting.jpeg"
Rename-Item -Path (Join-Path $folder "2011White Cake Chocolate Frosting.jpeg") -NewName "2011-white-cake-chocolate-frosting.jpeg"
Rename-Item -Path (Join-Path $folder "2012White Cake Vanilla Frosting.jpeg") -NewName "2012-white-cake-vanilla-frosting.jpeg"
Rename-Item -Path (Join-Path $folder "2013Cookies-M&M.jpeg") -NewName "2013-cookies-mandm.jpeg"
Rename-Item -Path (Join-Path $folder "201Amazing Machines Colossal Cranes .jpg") -NewName "201-amazing-machines-colossal-cranes.jpg"
Rename-Item -Path (Join-Path $folder "202American Born Chinese.jpg") -NewName "202-american-born-chinese.jpg"
Rename-Item -Path (Join-Path $folder "203Baby Boy, What Will You Be.jpeg") -NewName "203-baby-boy-what-will-you-be.jpeg"
Rename-Item -Path (Join-Path $folder "204Baby Sign Language.jpg") -NewName "204-baby-sign-language.jpg"
Rename-Item -Path (Join-Path $folder "205The Bad Guys Aliens VS Bad Guys.jpg") -NewName "205-bad-guys-alien-vs-bad-guys.jpg"
Rename-Item -Path (Join-Path $folder "206Black is a Rainbow Color.jpg") -NewName "206-black-is-a-rainbow-color.jpg"
Rename-Item -Path (Join-Path $folder "207Black Joy.jpg") -NewName "207-black-joy.jpg"
Rename-Item -Path (Join-Path $folder "208Black Panther.jpg") -NewName "208-black-panther-nation-under-our-feet.jpg"
Rename-Item -Path (Join-Path $folder "209Bletchley Riddle.jpg") -NewName "209-bletchley-riddle.jpg"
Rename-Item -Path (Join-Path $folder "210Cat's Cradle Book.jpg") -NewName "210-cat-cradle.jpg"
Rename-Item -Path (Join-Path $folder "211Cookie of Doom.jpg") -NewName "211-cookie-of-doom.jpg"
Rename-Item -Path (Join-Path $folder "212Dinosaur Day.png") -NewName "212-dinosaur-day.png"
Rename-Item -Path (Join-Path $folder "213Full, Full, Full of Love.jpg") -NewName "213-full-full-full-of-love.jpg"
Rename-Item -Path (Join-Path $folder "214Girls Like Me.jpg") -NewName "214-girls-like-me.jpg"
Rename-Item -Path (Join-Path $folder "215Goodnight Moon.jpg") -NewName "215-goodnight-moon.jpg"
Rename-Item -Path (Join-Path $folder "216Hair Love.jpg") -NewName "216-hair-love.jpg"
Rename-Item -Path (Join-Path $folder "217I Am Empowering African American for Boys.jpg") -NewName "217-i-am-empowering-african-american-for-boys.jpg"
Rename-Item -Path (Join-Path $folder "218I Am Empowering Black and Brown Girls Natural Curly Hair.jpg") -NewName "218-i-am-empowering-black-and-brown-girls-natural-girly-hair.jpg"
Rename-Item -Path (Join-Path $folder "219I Am Every Good Thing.jpg") -NewName "219-i-am-every-good-thing.jpg"
Rename-Item -Path (Join-Path $folder "220I Know Why the Caged Bird Sings.webp") -NewName "220-i-know-why-the-caged-bird-sings.webp"
Rename-Item -Path (Join-Path $folder "221Interesting Facts for Curious Minds.jpg") -NewName "221-interesting-facts-for-curious-minds.jpg"
Rename-Item -Path (Join-Path $folder "222I Promise.jpg") -NewName "222-i-promise.jpg"
Rename-Item -Path (Join-Path $folder "223Jabari Jumps.jpeg") -NewName "223-jabari-jumps.jpeg"
Rename-Item -Path (Join-Path $folder "224Life Skills for Teens.jpg") -NewName "224-life-skills-for-teens.jpg"
Rename-Item -Path (Join-Path $folder "225Mommy, What Do You See When You Look At Me.jpg") -NewName "225-mommy-what-do-you-see-when-you-look-at-me.jpg"
Rename-Item -Path (Join-Path $folder "226Parade of Elephants.jpg") -NewName "226-parade-of-elephants.jpg"
Rename-Item -Path (Join-Path $folder "227Sharks.jpg") -NewName "227-sharks.jpg"
Rename-Item -Path (Join-Path $folder "228Snowy Day.jpg") -NewName "228-snowy-day.jpg"
Rename-Item -Path (Join-Path $folder "229Teen Baking Cookbook.jpg") -NewName "229-super-easy-teen-baking-cookbook.jpg"
Rename-Item -Path (Join-Path $folder "230Unicorn Party Book.png") -NewName "230-unicorn-party.png"
Rename-Item -Path (Join-Path $folder "231Where Does Pizza Come From.jpg") -NewName "231-where-does-pizza-come-from.jpg"
Rename-Item -Path (Join-Path $folder "3000Paper Streamers.png") -NewName "3000-paper-streamers.png"
Rename-Item -Path (Join-Path $folder "3001Candles.png") -NewName "3001-candles.png"
Rename-Item -Path (Join-Path $folder "3002Scissors.png") -NewName "3002-scissors.png"
Rename-Item -Path (Join-Path $folder "3003Tape.png") -NewName "3003-tape.png"
Rename-Item -Path (Join-Path $folder "3004Gift bag 16White.png") -NewName "3004-gift-bag.png"
Rename-Item -Path (Join-Path $folder "3005Gift Bag 13White.png") -NewName "3005-gift-bag.png"
Rename-Item -Path (Join-Path $folder "3006Candle Bag 3 4.png") -NewName "3006-candle-bag.png"
Rename-Item -Path (Join-Path $folder "3007Gift Bag 13Blue.png") -NewName "3007-gift-bag.png"
Rename-Item -Path (Join-Path $folder "3008Candle Bag 3 4.png") -NewName "3008-gift-bag.png"
Rename-Item -Path (Join-Path $folder "3009Candle Bag 2 3.png") -NewName "3009-candle-bag.png"
Rename-Item -Path (Join-Path $folder "300Bananagrams.jpg") -NewName "300-bananagrams.jpg"
Rename-Item -Path (Join-Path $folder "301CandyLand.jpg") -NewName "301-candyland.jpg"
Rename-Item -Path (Join-Path $folder "302Checkers.jpg") -NewName "302-checkers.jpg"
Rename-Item -Path (Join-Path $folder "303Chess, Checkers, Tic Tac Toe.jpg") -NewName "303-chess-checkers-tic-tac-toe.jpg"
Rename-Item -Path (Join-Path $folder "304Chutes and Ladders.jpg") -NewName "304-chutes-and-ladders.jpg"
Rename-Item -Path (Join-Path $folder "305Connect 4 Board.jpg") -NewName "305-connect-4-board.jpg"
Rename-Item -Path (Join-Path $folder "306Deck of Playing Cards.webp") -NewName "306-deck-of-playing-cards.webp"
Rename-Item -Path (Join-Path $folder "307Dungeon & Dragons Dice Set.jpg") -NewName "307-dungeon-and-dragons-dice-set.jpg"
Rename-Item -Path (Join-Path $folder "308Dungeon & Dragons Mad Libs.jpg") -NewName "308-dungeon-and-dragons-mad-libs.jpg"
Rename-Item -Path (Join-Path $folder "309Dungeon & Dragons Mini Dice.jpg") -NewName "309-dungeon-and-dragons-mini-dice.jpg"
Rename-Item -Path (Join-Path $folder "310Fabric Dart Board.png") -NewName "310-fabric-dart-board.png"
Rename-Item -Path (Join-Path $folder "311Jenga.jpg") -NewName "311-jenga.jpg"
Rename-Item -Path (Join-Path $folder "312Math Dice Jr..jpg") -NewName "312-math-dice-jr.jpg"
Rename-Item -Path (Join-Path $folder "313Rat-a-tat Cat.jpg") -NewName "313-rat-a-tat-cat.jpg"
Rename-Item -Path (Join-Path $folder "314Scrabble.jpg") -NewName "314-scrabble.jpg"
Rename-Item -Path (Join-Path $folder "315Seek-a-Boo.jfif") -NewName "315-seek-a-boo.jfif"
Rename-Item -Path (Join-Path $folder "316Sensory Bin - Outer Space.jpg") -NewName "316-sensory-bin-outer-space.jpg"
Rename-Item -Path (Join-Path $folder "317Slapzi.jpg") -NewName "317-slapzi.jpg"
Rename-Item -Path (Join-Path $folder "318Sleeping Queens.png") -NewName "318-sleeping-queens.png"
Rename-Item -Path (Join-Path $folder "319Sorry.jpg") -NewName "319-sorry.jpg"
Rename-Item -Path (Join-Path $folder "320Splash Cards.jpg") -NewName "320-splash-cards.jpg"
Rename-Item -Path (Join-Path $folder "321Stress(No) Chess.png") -NewName "321-stress-no-chess.png"
Rename-Item -Path (Join-Path $folder "322Trouble Board.jpg") -NewName "322-trouble-board.jpg"
Rename-Item -Path (Join-Path $folder "323Uno.jpg") -NewName "323-uno.jpg"
Rename-Item -Path (Join-Path $folder "324Yahtzee.jpg") -NewName "324-yahtzee.jpg"
Rename-Item -Path (Join-Path $folder "400Acrylic Art Paint Set.jpg") -NewName "400-acrylic-art-paint-set.jpg"
Rename-Item -Path (Join-Path $folder "401Baby Sensory Crinkle Paper.jpg") -NewName "401-baby-sensory-crinkle-paper.jpg"
Rename-Item -Path (Join-Path $folder "402Bunch O Balloons.jpg") -NewName "402-bunch-o-balloons.jpg"
Rename-Item -Path (Join-Path $folder "403Classic Color Markers.webp") -NewName "403-classic-color-markers.webp"
Rename-Item -Path (Join-Path $folder "404Colored Pencils.png") -NewName "404-colored-pencils.png"
Rename-Item -Path (Join-Path $folder "405Drawing Kit.jpg") -NewName "405-drawing-kit.jpg"
Rename-Item -Path (Join-Path $folder "406Drawing Pad.jpg") -NewName "406-drawing-pad.jpg"
Rename-Item -Path (Join-Path $folder "407Fingerprint Activities Animals Spiral-bound.jpg") -NewName "407-fingerprint-activities-animals-spiral-bound.jpg"
Rename-Item -Path (Join-Path $folder "408Friendship Bracelet Thread.jpg") -NewName "408-friendship-bracelet-thread.jpg"
Rename-Item -Path (Join-Path $folder "409Hey Clay.png") -NewName "409-hey-clay.png"
Rename-Item -Path (Join-Path $folder "410How to Write And Draw Your Own Comics.webp") -NewName "410-how-to-write-and-draw-your-own-comics.webp"
Rename-Item -Path (Join-Path $folder "411Kinetic Sand.png") -NewName "411-kinetic-sand.png"
Rename-Item -Path (Join-Path $folder "412Liquid Motion Bubbler.jpg") -NewName "412-liquid-motion-bubbler.jpg"
Rename-Item -Path (Join-Path $folder "413Modeling Clay.jpg") -NewName "413-modeling-clay.jpg"
Rename-Item -Path (Join-Path $folder "414Pin Art.jpg") -NewName "414-pin-art.jpg"
Rename-Item -Path (Join-Path $folder "415Shape Makers.jpg") -NewName "415-shape-markers.jpg"
Rename-Item -Path (Join-Path $folder "416Sharpies Color Burst.jpg") -NewName "416-sharpies-color-burst.jpg"
Rename-Item -Path (Join-Path $folder "417Sketch Pad.jpg") -NewName "417-sketch-pad.jpg"
Rename-Item -Path (Join-Path $folder "418Travel Easel.png") -NewName "418-travel-easel.png"
Rename-Item -Path (Join-Path $folder "500Beaded Bracelet.jpg") -NewName "500-beaded-bracelet.jpg"
Rename-Item -Path (Join-Path $folder "501Good Vibes Necklace.jpg") -NewName "501-good-vibes-necklace.jpg"
Rename-Item -Path (Join-Path $folder "502Initial Necklace.webp") -NewName "502-initial-necklace.webp"
Rename-Item -Path (Join-Path $folder "503Layered necklace.jpg") -NewName "503-layered-necklace.jpg"
Rename-Item -Path (Join-Path $folder "504Leather Bracelet.jpg") -NewName "504-leather-bracelet.jpg"
Rename-Item -Path (Join-Path $folder "505Leather Wrap Bracelets.jpg") -NewName "505-leather-wrap-bracelets.jpg"
Rename-Item -Path (Join-Path $folder "506Multilayer Bracelet.jpg") -NewName "506-multilayer-bracelet.jpg"
Rename-Item -Path (Join-Path $folder "507Tree of Life Bracelets.jpg") -NewName "507-tree-of-life-bracelets.jpg"
Rename-Item -Path (Join-Path $folder "508Twisted Rope Chain.jpg") -NewName "508-twisted-rope-chain.jpg"
Rename-Item -Path (Join-Path $folder "600Balls for Toddler .png") -NewName "600-balls-for-toddler.png"
Rename-Item -Path (Join-Path $folder "601Baseball 3 in 1 Set for Kids 3-5 - Tee Ball Stand, Hanging Tee, Ball Launcher and 6 Softballs - Adjustable Height.jpg") -NewName "601-baseball-3-in-1-set-for-kids-3-5-adjustable-height.jpg"
Rename-Item -Path (Join-Path $folder "602Basketball.jpg") -NewName "602-basketball.jpg"
Rename-Item -Path (Join-Path $folder "603Basketball Kids.jpg") -NewName "603-basketball-kids.jpg"
Rename-Item -Path (Join-Path $folder "604Basketball Youth.jpg") -NewName "604-basketball-youth.jpg"
Rename-Item -Path (Join-Path $folder "605Double Jump Rope.png") -NewName "605-double-jump-rope.png"
Rename-Item -Path (Join-Path $folder "606Fishing Rod and Reel Combo.jpg") -NewName "606-fishing-rod-and-reel-combo.jpg"
Rename-Item -Path (Join-Path $folder "607Football.jpg") -NewName "607-football.jpg"
Rename-Item -Path (Join-Path $folder "608Footbal - Chiefs.jpg") -NewName "608-footbal-chiefs.jpg"
Rename-Item -Path (Join-Path $folder "609Footbal Kicking Tee.jpg") -NewName "609-footbal-kicking-tee.jpg"
Rename-Item -Path (Join-Path $folder "610Football Youth.jpg") -NewName "610-football-youth.jpg"
Rename-Item -Path (Join-Path $folder "611L.O.L. Surprise! Quad Adjustable Roller Skate.png") -NewName "611-l-o-l-surprise-quad-adjustable-roller-skate.png"
Rename-Item -Path (Join-Path $folder "612Mini Basketball Hoop.jpg") -NewName "612-mini-basketball-hoop.jpg"
Rename-Item -Path (Join-Path $folder "613Pro Vision 31 Skateboard.jpg") -NewName "613-pro-vision-31-skateboard.jpg"
Rename-Item -Path (Join-Path $folder "614Punt, Pass And Shoot Ball Set.webp") -NewName "614-punt-pass-and-shoot-ball-set.webp"
Rename-Item -Path (Join-Path $folder "615ush & Pop Bulldozer.jpg") -NewName "615-push-and-pop-bulldozer.jpg"
Rename-Item -Path (Join-Path $folder "616Razor A Kick Scooter.png") -NewName "616-razor-a-kick-scooter.png"
Rename-Item -Path (Join-Path $folder "617Single Jump Rope.png") -NewName "617-single-jump-rope.png"
Rename-Item -Path (Join-Path $folder "618Soccer Ball.jpg") -NewName "618-soccer-ball.jpg"
Rename-Item -Path (Join-Path $folder "619Soccer Ball - youth.jpg") -NewName "619-soccer-ball-youth.jpg"
Rename-Item -Path (Join-Path $folder "620Sonic Fin Football.jpg") -NewName "620-sonic-fin-football.jpg"
Rename-Item -Path (Join-Path $folder "621Youth Inline Skate.png") -NewName "621-youth-inline-skate.png"
Rename-Item -Path (Join-Path $folder "700Break Open Geode.jpg") -NewName "700-break-open-geode.jpg"
Rename-Item -Path (Join-Path $folder "701Color Changing Cup.jpg") -NewName "701-color-changing-cup.jpg"
Rename-Item -Path (Join-Path $folder "702Croc Charms.jpg") -NewName "702-croc-charms.jpg"
Rename-Item -Path (Join-Path $folder "703Crossbody Backback.jpg") -NewName "703-crossbody-backback.jpg"
Rename-Item -Path (Join-Path $folder "704Personalized Blanket.webp") -NewName "704-personalized-blanket.webp"
Rename-Item -Path (Join-Path $folder "705Shark Hooded Baby Towel.png") -NewName "705-shark-hooded-baby-towel.png"
Rename-Item -Path (Join-Path $folder "706Thermos Sports Jug.jpg") -NewName "706-thermos-sports-jug.jpg"
Rename-Item -Path (Join-Path $folder "707Towels.jpg") -NewName "707-towels.jpg"
Rename-Item -Path (Join-Path $folder "708Water Bottle for kids.jpg") -NewName "708-water-bottle-for-kids.jpg"
Rename-Item -Path (Join-Path $folder "709Water Cup - Large.jpg") -NewName "709-water-cup-large.jpg"
Rename-Item -Path (Join-Path $folder "710Water Cup - Medium.jpg") -NewName "710-water-cup-medium.jpg"
Rename-Item -Path (Join-Path $folder "711White Fuzzy Rug.jpg") -NewName "711-white-fuzzy-rug.jpg"
Rename-Item -Path (Join-Path $folder "712Its My Birthday Pin.jpg") -NewName "712-it-s-my-birthday-pin.jpg"
Rename-Item -Path (Join-Path $folder "800Old Navy Gift Card.jpg") -NewName "800-old-navy.jpg"
Rename-Item -Path (Join-Path $folder "801PH Coffee Gift card.png") -NewName "801-ph-coffee.png"
Rename-Item -Path (Join-Path $folder "802Subway Gift Card.png") -NewName "802-subway.png"
Rename-Item -Path (Join-Path $folder "803Chipotle Gift Card.jpg") -NewName "803-chipotle.jpg"
Rename-Item -Path (Join-Path $folder "804TJ Maxx Gfit Card.jpg") -NewName "804-tj-maxx.jpg"
Rename-Item -Path (Join-Path $folder "805Sky Zone Gift Card.webp") -NewName "805-sky-zone.webp"
Rename-Item -Path (Join-Path $folder "806Cici's Pizza Gift Card.png") -NewName "806-cici-s.png"
Rename-Item -Path (Join-Path $folder "807Ulta Gift card.jpg") -NewName "807-ulta.jpg"
Rename-Item -Path (Join-Path $folder "808QuikTrip Gift card.jpg") -NewName "808-quiktrip.jpg"
Rename-Item -Path (Join-Path $folder "809Little Caesar's Pizza Gift Card.webp") -NewName "809-little-caesar-s.webp"
Rename-Item -Path (Join-Path $folder "810Fritz's Gift Card.webp") -NewName "810-fritz-s.webp"
Rename-Item -Path (Join-Path $folder "811Yogurtini Gift Card.png") -NewName "811-yogurtini.png"
Rename-Item -Path (Join-Path $folder "812Dairy Queen Gift Card.jpg") -NewName "812-dairy-queen.jpg"
Rename-Item -Path (Join-Path $folder "813Pizza Street Gift Card 9-under.jpg") -NewName "813-pizza-street.jpg"
Rename-Item -Path (Join-Path $folder "814Pizza Street Gift Card 10-Over.jpg") -NewName "814-pizza-street.jpg"
Rename-Item -Path (Join-Path $folder "815Nut Allergy Needs Gift Card.jpg") -NewName "815-nut-allergy-gift-card.jpg"
Rename-Item -Path (Join-Path $folder "900Alarm Clock & Sound Machine.jpg") -NewName "900-alarm-clock-and-sound-machine.jpg"
Rename-Item -Path (Join-Path $folder "901Headphones - Wireless.jpg") -NewName "901-headphones-wireless.jpg"
Rename-Item -Path (Join-Path $folder "902Lava Lamp.png") -NewName "902-lava-lamp.png"