// src/data.js

// CATEGORY DEFINITIONS
// colorClass values match CSS classes in App.css
export const CATEGORIES = [
  { id: "browse-all",     name: "Browse all",     colorClass: "purple"   },
  { id: "toys",           name: "Toys",           colorClass: "pink"     },
  { id: "books",          name: "Books",          colorClass: "blue"     },
  { id: "sports",         name: "Sports",         colorClass: "green"    },
  { id: "games",          name: "Games",          colorClass: "yellow"   },
  { id: "gift-cards",     name: "Gift Cards",     colorClass: "peach"    },
  { id: "electronics",    name: "Electronics",    colorClass: "cyan"     },
  { id: "jewelry",        name: "Jewelry",        colorClass: "lavender" },
  { id: "arts-and-crafts",name: "Arts & Crafts",  colorClass: "coral"    },
  { id: "misc",           name: "Misc.",          colorClass: "mint"     },
  { id: "sweet-treats",   name: "Sweet Treats",   colorClass: "peach"    },
];


// PRODUCT DEFINITIONS
// Each key must match a category id (except "browse-all", which is special)
export const PRODUCTS = {
  "arts-and-crafts":   [
    {
      "id": 400,
      "name": "Acrylic Art Paint Set",
      "description": "Painting Set",
      "categoryId": "arts-and-crafts",
      "cost": 27,
      "price": 27,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "400Acrylic Art Paint Set.jpg"
    },
    {
      "id": 401,
      "name": "Baby Sensory Crinkle Paper",
      "description": "Crinkle paper",
      "categoryId": "arts-and-crafts",
      "cost": 8,
      "price": 7,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "401Baby Sensory Crinkle Paper.jpg"
    },
    {
      "id": 402,
      "name": "Bunch O Balloons",
      "description": "Water Balloons",
      "categoryId": "arts-and-crafts",
      "cost": 17,
      "price": 17,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "402Bunch O Balloons.jpg"
    },
    {
      "id": 403,
      "name": "Classic Color Markers",
      "description": "Crayola Markers",
      "categoryId": "arts-and-crafts",
      "cost": 5,
      "price": 5,
      "ageRange": "3-10",
      "minAge": 3,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "403Classic Color Markers.webp"
    },
    {
      "id": 404,
      "name": "Colored Pencils",
      "description": "48 Colored Pencils",
      "categoryId": "arts-and-crafts",
      "cost": 28,
      "price": 28,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "404Colored Pencils.png"
    },
    {
      "id": 405,
      "name": "Drawing Kit",
      "description": "103 Portable Zipper Case",
      "categoryId": "arts-and-crafts",
      "cost": 28,
      "price": 25,
      "ageRange": "11-18",
      "minAge": 11,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "405Drawing Kit.jpg"
    },
    {
      "id": 406,
      "name": "Drawing Pad",
      "description": "Sketching Pad",
      "categoryId": "arts-and-crafts",
      "cost": 8,
      "price": 20,
      "ageRange": "11-18",
      "minAge": 11,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "406Drawing Pad.jpg"
    },
    {
      "id": 407,
      "name": "Fingerprint Activities Animals Spiral-bound",
      "description": "Finger Painting",
      "categoryId": "arts-and-crafts",
      "cost": 15,
      "price": 15,
      "ageRange": "5-9",
      "minAge": 5,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "407Fingerprint Activities Animals Spiral-bound.jpg"
    },
    {
      "id": 408,
      "name": "Friendship Bracelet Thread",
      "description": "50+ colorful bracelet making",
      "categoryId": "arts-and-crafts",
      "cost": 10,
      "price": 6,
      "ageRange": "9-18",
      "minAge": 9,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "408Friendship Bracelet Thread.jpg"
    },
    {
      "id": 409,
      "name": "Hey Clay",
      "description": "Non sticky, toxic 5 cans Clay",
      "categoryId": "arts-and-crafts",
      "cost": 6,
      "price": 6,
      "ageRange": "4-15",
      "minAge": 4,
      "maxAge": 15,
      "ageGroup": "5to12",
      "image": "409Hey Clay.png"
    },
    {
      "id": 410,
      "name": "How to Write And Draw Your Own Comics",
      "description": "Intro to Comic book",
      "categoryId": "arts-and-crafts",
      "cost": 12,
      "price": 13,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "410How to Write And Draw Your Own Comics.webp"
    },
    {
      "id": 411,
      "name": "Kinetic Sand",
      "description": "Sand never dries out",
      "categoryId": "arts-and-crafts",
      "cost": 21,
      "price": 21,
      "ageRange": "9-18",
      "minAge": 9,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "411Kinetic Sand.png"
    },
    {
      "id": 412,
      "name": "Liquid Motion Bubbler",
      "description": "Sensory fidget",
      "categoryId": "arts-and-crafts",
      "cost": 9,
      "price": 8,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "412Liquid Motion Bubbler.jpg"
    },
    {
      "id": 413,
      "name": "Modeling Clay",
      "description": "8 Colors of Clay",
      "categoryId": "arts-and-crafts",
      "cost": 8,
      "price": 9,
      "ageRange": "4-10",
      "minAge": 4,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "413Modeling Clay.jpg"
    },
    {
      "id": 414,
      "name": "Pin Art",
      "description": "Fidget Impression Board",
      "categoryId": "arts-and-crafts",
      "cost": 13,
      "price": 9,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "414Pin Art.jpg"
    },
    {
      "id": 415,
      "name": "Shape Markers",
      "description": "Magnetic Foam Puzzles",
      "categoryId": "arts-and-crafts",
      "cost": 16,
      "price": 13,
      "ageRange": "6-11",
      "minAge": 6,
      "maxAge": 11,
      "ageGroup": "5to12",
      "image": "415Shape Makers.jpg"
    },
    {
      "id": 416,
      "name": "Sharpies Color Burst",
      "description": "Fine Point 12 Markers",
      "categoryId": "arts-and-crafts",
      "cost": 18,
      "price": 16,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "416Sharpies Color Burst.jpg"
    },
    {
      "id": 417,
      "name": "Sketch Pad",
      "description": "100 Sheets Paper",
      "categoryId": "arts-and-crafts",
      "cost": 18,
      "price": 8,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "417Sketch Pad.jpg"
    },
    {
      "id": 418,
      "name": "Travel Easel",
      "description": "37-Piece Art&Easel",
      "categoryId": "arts-and-crafts",
      "cost": 26,
      "price": 26,
      "ageRange": "4-7",
      "minAge": 4,
      "maxAge": 7,
      "ageGroup": "5to12",
      "image": "418Travel Easel.png"
    }
  ],
  "books":   [
    {
      "id": 200,
      "name": "Amazing Machines: Big Bulldozers",
      "description": "Huge machines, digging fun",
      "categoryId": "books",
      "cost": 8,
      "price": 8,
      "ageRange": "4-6",
      "minAge": 4,
      "maxAge": 6,
      "ageGroup": "5to12",
      "image": "200Neighbors Garage.jpg"
    },
    {
      "id": 201,
      "name": "Amazing Machines: Colossal Cranes",
      "description": "Tall machines, heavy lifting",
      "categoryId": "books",
      "cost": 9,
      "price": 9,
      "ageRange": "4-6",
      "minAge": 4,
      "maxAge": 6,
      "ageGroup": "5to12",
      "image": "201Amazing Machines Colossal Cranes .jpg"
    },
    {
      "id": 202,
      "name": "American Born Chinese",
      "description": "Jin Wang moves into a neighborhood to discover he is the only Chinese-American student at his new school.",
      "categoryId": "books",
      "cost": 10,
      "price": 10,
      "ageRange": "4-6",
      "minAge": 4,
      "maxAge": 6,
      "ageGroup": "5to12",
      "image": "202American Born Chinese.jpg"
    },
    {
      "id": 203,
      "name": "Baby Boy, What Will You Be?",
      "description": "A book on possible life achievements for a child",
      "categoryId": "books",
      "cost": 12,
      "price": 12,
      "ageRange": "3-7",
      "minAge": 3,
      "maxAge": 7,
      "ageGroup": "5to12",
      "image": "203Baby Boy, What Will You Be.jpeg"
    },
    {
      "id": 204,
      "name": "Baby Sign Language",
      "description": "Everyday baby sign language book",
      "categoryId": "books",
      "cost": 7,
      "price": 7,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "204Baby Sign Language.jpg"
    },
    {
      "id": 205,
      "name": "Bad Guys Alien vs Bad Guys",
      "description": "Imaginary world of dinosaur playing, splashing, and singing. Coloring book.",
      "categoryId": "books",
      "cost": 8,
      "price": 8,
      "ageRange": "6-10",
      "minAge": 6,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "205The Bad Guys Aliens VS Bad Guys.jpg"
    },
    {
      "id": 206,
      "name": "Black Is a Rainbow Color",
      "description": "Celebration, love, powerful voices",
      "categoryId": "books",
      "cost": 9,
      "price": 9,
      "ageRange": "4-8",
      "minAge": 4,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "206Black is a Rainbow Color.jpg"
    },
    {
      "id": 207,
      "name": "Black Joy",
      "description": "Celebrating",
      "categoryId": "books",
      "cost": 9,
      "price": 9,
      "ageRange": "4-8",
      "minAge": 4,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "207Black Joy.jpg"
    },
    {
      "id": 208,
      "name": "Black Panther: Nation Under Our Feet",
      "description": "Superhero, King with Brave Battles",
      "categoryId": "books",
      "cost": 9,
      "price": 9,
      "ageRange": "6-10",
      "minAge": 6,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "208Black Panther.jpg"
    },
    {
      "id": 209,
      "name": "Bletchley Riddle",
      "description": "Mystery solving",
      "categoryId": "books",
      "cost": 10,
      "price": 10,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "209Bletchley Riddle.jpg"
    },
    {
      "id": 210,
      "name": "Cat' Cradle",
      "description": "Science Fiction",
      "categoryId": "books",
      "cost": null,
      "price": null,
      "ageRange": "8-12",
      "minAge": 8,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "210Cat's Cradle Book.jpg"
    },
    {
      "id": 211,
      "name": "Cookie of Doom",
      "description": "Fortune Cookie Story",
      "categoryId": "books",
      "cost": 8,
      "price": 8,
      "ageRange": "8-12",
      "minAge": 8,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "211Cookie of Doom.jpg"
    },
    {
      "id": 212,
      "name": "Dinosaur Day",
      "description": "Rhyming Book to learn Dinosaurs",
      "categoryId": "books",
      "cost": 5,
      "price": 5,
      "ageRange": "4-8",
      "minAge": 4,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "212Dinosaur Day.png"
    },
    {
      "id": 213,
      "name": "Full,Full,Full of Love",
      "description": "Joys of family and food.",
      "categoryId": "books",
      "cost": 6,
      "price": 6,
      "ageRange": "1-5",
      "minAge": 1,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "213Full, Full, Full of Love.jpg"
    },
    {
      "id": 214,
      "name": "Girls Like Me",
      "description": "Girls like me",
      "categoryId": "books",
      "cost": 12,
      "price": 12,
      "ageRange": "3-9",
      "minAge": 3,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "214Girls Like Me.jpg"
    },
    {
      "id": 215,
      "name": "Goodnight Moon",
      "description": "Classic bedtime story.",
      "categoryId": "books",
      "cost": 6,
      "price": 6,
      "ageRange": "1-4",
      "minAge": 1,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "215Goodnight Moon.jpg"
    },
    {
      "id": 216,
      "name": "Hair Love",
      "description": "Love between fathers and daughters through hair care.",
      "categoryId": "books",
      "cost": 10,
      "price": 10,
      "ageRange": "1-4",
      "minAge": 1,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "216Hair Love.jpg"
    },
    {
      "id": 217,
      "name": "I am Empowering African American for Boys",
      "description": "What it means to be confident, brave, and kind.",
      "categoryId": "books",
      "cost": 10,
      "price": 10,
      "ageRange": "2-6",
      "minAge": 2,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "217I Am Empowering African American for Boys.jpg"
    },
    {
      "id": 218,
      "name": "I am Empowering Black and Brown Girls Natural Girly Hair",
      "description": "Building confidence, self-esteem, imagination, and spirit. Coloring book.",
      "categoryId": "books",
      "cost": 10,
      "price": 10,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "218I Am Empowering Black and Brown Girls Natural Curly Hair.jpg"
    },
    {
      "id": 219,
      "name": "I Am Every Good Thing",
      "description": "Upbeat, empowering. Recognizing who we are.",
      "categoryId": "books",
      "cost": 13,
      "price": 13,
      "ageRange": "3-9",
      "minAge": 3,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "219I Am Every Good Thing.jpg"
    },
    {
      "id": 220,
      "name": "I Know Why the Caged Bird Sings",
      "description": "Challenging struggles the authour went through in early years of life.",
      "categoryId": "books",
      "cost": 8,
      "price": 8,
      "ageRange": "15-18",
      "minAge": 15,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "220I Know Why the Caged Bird Sings.webp"
    },
    {
      "id": 221,
      "name": "Interesting Facts for Curious Minds",
      "description": "Book with interesting facts.",
      "categoryId": "books",
      "cost": 13,
      "price": 13,
      "ageRange": "10-15",
      "minAge": 10,
      "maxAge": 15,
      "ageGroup": "12plus",
      "image": "221Interesting Facts for Curious Minds.jpg"
    },
    {
      "id": 222,
      "name": "I Promise",
      "description": "LeBron Jamess motivates children everywhere to always strive for greatness.",
      "categoryId": "books",
      "cost": 12,
      "price": 12,
      "ageRange": "4-8",
      "minAge": 4,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "222I Promise.jpg"
    },
    {
      "id": 223,
      "name": "Jabari Jumps",
      "description": "Overcoming fears.",
      "categoryId": "books",
      "cost": 7,
      "price": 7,
      "ageRange": "4-9",
      "minAge": 4,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "223Jabari Jumps.jpeg"
    },
    {
      "id": 224,
      "name": "Life Skills for Teens",
      "description": "Teens",
      "categoryId": "books",
      "cost": 9,
      "price": 9,
      "ageRange": "13-17",
      "minAge": 13,
      "maxAge": 17,
      "ageGroup": "12plus",
      "image": "224Life Skills for Teens.jpg"
    },
    {
      "id": 225,
      "name": "Mommy, What Do You See, When You Look At Me",
      "description": "Daughter challenges mom to answer questions.",
      "categoryId": "books",
      "cost": 10,
      "price": 10,
      "ageRange": "2-9",
      "minAge": 2,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "225Mommy, What Do You See When You Look At Me.jpg"
    },
    {
      "id": 226,
      "name": "Parade of Elephants",
      "description": "Introduces basic concepts.",
      "categoryId": "books",
      "cost": 8,
      "price": 8,
      "ageRange": "1-4",
      "minAge": 1,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "226Parade of Elephants.jpg"
    },
    {
      "id": 227,
      "name": "Sharks",
      "description": "Shark facts.",
      "categoryId": "books",
      "cost": 5,
      "price": 5,
      "ageRange": "4-8",
      "minAge": 4,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "227Sharks.jpg"
    },
    {
      "id": 228,
      "name": "Snowy Day",
      "description": "Exploring a neighborhood after the first snow.",
      "categoryId": "books",
      "cost": 4,
      "price": 4,
      "ageRange": "1-4",
      "minAge": 1,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "228Snowy Day.jpg"
    },
    {
      "id": 229,
      "name": "Super Easy Teen Baking Cookbook",
      "description": "60 Simple Recipe",
      "categoryId": "books",
      "cost": 10,
      "price": 10,
      "ageRange": "13-16",
      "minAge": 13,
      "maxAge": 16,
      "ageGroup": "12plus",
      "image": "229Teen Baking Cookbook.jpg"
    },
    {
      "id": 230,
      "name": "Unicorn Party",
      "description": "Six playful unicorns gather for a magical party. Coloring book.",
      "categoryId": "books",
      "cost": 8,
      "price": 8,
      "ageRange": "6-11",
      "minAge": 6,
      "maxAge": 11,
      "ageGroup": "5to12",
      "image": "230Unicorn Party Book.png"
    },
    {
      "id": 231,
      "name": "Where Does Pizza Come From?",
      "description": "Coloring",
      "categoryId": "books",
      "cost": 8,
      "price": 8,
      "ageRange": "4-9",
      "minAge": 4,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "231Where Does Pizza Come From.jpg"
    }
  ],
  "electronics":   [
    {
      "id": 900,
      "name": "Alarm Clock & Sound Machine",
      "description": "Sleep & Relax",
      "categoryId": "electronics",
      "cost": 20,
      "price": 20,
      "ageRange": "7-18",
      "minAge": 7,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "900Alarm Clock & Sound Machine.jpg"
    },
    {
      "id": 901,
      "name": "Headphones - Wireless",
      "description": "Wireless Microphone",
      "categoryId": "electronics",
      "cost": 25,
      "price": 20,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "901Headphones - Wireless.jpg"
    },
    {
      "id": 902,
      "name": "Lava Lamp",
      "description": "Swirling Colorful Glow DÃ©cor",
      "categoryId": "electronics",
      "cost": 32,
      "price": 30,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "902Lava Lamp.png"
    }
  ],
  "games":   [
    {
      "id": 300,
      "name": "Bananagrams",
      "description": "Fast Paced Word Game",
      "categoryId": "games",
      "cost": 16,
      "price": 16,
      "ageRange": "7-18",
      "minAge": 7,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "300Bananagrams.jpg"
    },
    {
      "id": 301,
      "name": "CandyLand",
      "description": "Classic Board Game",
      "categoryId": "games",
      "cost": 13,
      "price": 13,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "301CandyLand.jpg"
    },
    {
      "id": 302,
      "name": "Checkers",
      "description": "Classic Board Game",
      "categoryId": "games",
      "cost": 10,
      "price": 10,
      "ageRange": "6-9",
      "minAge": 6,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "302Checkers.jpg"
    },
    {
      "id": 303,
      "name": "Chess, Checkers, Tic Tac Toe",
      "description": "Classic Board Game",
      "categoryId": "games",
      "cost": 20,
      "price": 20,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "303Chess, Checkers, Tic Tac Toe.jpg"
    },
    {
      "id": 304,
      "name": "Chutes and Ladders",
      "description": "Classic Board Game",
      "categoryId": "games",
      "cost": 9,
      "price": 9,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "304Chutes and Ladders.jpg"
    },
    {
      "id": 305,
      "name": "Connect 4 Board",
      "description": "Classic Board Game",
      "categoryId": "games",
      "cost": 9,
      "price": 9,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "305Connect 4 Board.jpg"
    },
    {
      "id": 306,
      "name": "Deck of Playing Cards",
      "description": "Classic Playing Cards",
      "categoryId": "games",
      "cost": 5,
      "price": 5,
      "ageRange": "6-18",
      "minAge": 6,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "306Deck of Playing Cards.webp"
    },
    {
      "id": 307,
      "name": "Dungeon & Dragons Dice Set",
      "description": "Dice Set",
      "categoryId": "games",
      "cost": 7,
      "price": 7,
      "ageRange": "16-18",
      "minAge": 16,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "307Dungeon & Dragons Dice Set.jpg"
    },
    {
      "id": 308,
      "name": "Dungeon & Dragons Mad Libs",
      "description": "Mad Libs",
      "categoryId": "games",
      "cost": 5,
      "price": 10,
      "ageRange": "16-18",
      "minAge": 16,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "308Dungeon & Dragons Mad Libs.jpg"
    },
    {
      "id": 309,
      "name": "Dungeon & Dragons Mini Dice",
      "description": "7 Piece Metal Dice Set",
      "categoryId": "games",
      "cost": 15,
      "price": 15,
      "ageRange": "16-18",
      "minAge": 16,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "309Dungeon & Dragons Mini Dice.jpg"
    },
    {
      "id": 310,
      "name": "Fabric Dart Board",
      "description": "Round hook-and-loop balls are the darts.",
      "categoryId": "games",
      "cost": 18,
      "price": 18,
      "ageRange": "4-12",
      "minAge": 4,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "310Fabric Dart Board.png"
    },
    {
      "id": 311,
      "name": "Jenga",
      "description": "Classic game of skill and strategy",
      "categoryId": "games",
      "cost": 11,
      "price": 11,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "311Jenga.jpg"
    },
    {
      "id": 312,
      "name": "Math Dice Jr.",
      "description": "Math Game",
      "categoryId": "games",
      "cost": 14,
      "price": 14,
      "ageRange": "6-12",
      "minAge": 6,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "312Math Dice Jr..jpg"
    },
    {
      "id": 313,
      "name": "Rat-a-tat Cat",
      "description": "Strategic Card Game",
      "categoryId": "games",
      "cost": 9,
      "price": 11,
      "ageRange": "6-13",
      "minAge": 6,
      "maxAge": 13,
      "ageGroup": "5to12",
      "image": "313Rat-a-tat Cat.jpg"
    },
    {
      "id": 314,
      "name": "Scrabble",
      "description": "Classic Board Game",
      "categoryId": "games",
      "cost": 22,
      "price": 10,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "314Scrabble.jpg"
    },
    {
      "id": 315,
      "name": "Seek-a-Boo",
      "description": "Memory Game",
      "categoryId": "games",
      "cost": 22,
      "price": 10,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "315Seek-a-Boo.jfif"
    },
    {
      "id": 316,
      "name": "Sensory Bin - Outer Space",
      "description": "Explore and Learn Hands On",
      "categoryId": "games",
      "cost": 20,
      "price": 20,
      "ageRange": "4-13",
      "minAge": 4,
      "maxAge": 13,
      "ageGroup": "5to12",
      "image": "316Sensory Bin - Outer Space.jpg"
    },
    {
      "id": 317,
      "name": "Slapzi",
      "description": "Fast Paced Picture Game",
      "categoryId": "games",
      "cost": 22,
      "price": 22,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "317Slapzi.jpg"
    },
    {
      "id": 318,
      "name": "Sleeping Queens",
      "description": "Strategic/Thinking Card Game",
      "categoryId": "games",
      "cost": 14,
      "price": 14,
      "ageRange": "9-18",
      "minAge": 9,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "318Sleeping Queens.png"
    },
    {
      "id": 319,
      "name": "Sorry",
      "description": "Classic Board Game",
      "categoryId": "games",
      "cost": 10,
      "price": 10,
      "ageRange": "6-15",
      "minAge": 6,
      "maxAge": 15,
      "ageGroup": "5to12",
      "image": "319Sorry.jpg"
    },
    {
      "id": 320,
      "name": "Splash Cards",
      "description": "Learning & Development",
      "categoryId": "games",
      "cost": 10,
      "price": 10,
      "ageRange": "3-7",
      "minAge": 3,
      "maxAge": 7,
      "ageGroup": "5to12",
      "image": "320Splash Cards.jpg"
    },
    {
      "id": 321,
      "name": "Stress(No) Chess",
      "description": "Learn Chess w/o Stress",
      "categoryId": "games",
      "cost": 13,
      "price": 13,
      "ageRange": "5-18",
      "minAge": 5,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "321Stress(No) Chess.png"
    },
    {
      "id": 322,
      "name": "Trouble Board",
      "description": "Classic Board Game",
      "categoryId": "games",
      "cost": 9,
      "price": 9,
      "ageRange": "5-18",
      "minAge": 5,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "322Trouble Board.jpg"
    },
    {
      "id": 323,
      "name": "Uno",
      "description": "Matching Colors & Numbers",
      "categoryId": "games",
      "cost": 5,
      "price": 7,
      "ageRange": "7-18",
      "minAge": 7,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "323Uno.jpg"
    },
    {
      "id": 324,
      "name": "Yahtzee",
      "description": "Classic Dice Game",
      "categoryId": "games",
      "cost": 9,
      "price": 9,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "324Yahtzee.jpg"
    }
  ],
  "gift-cards":   [
    {
      "id": 800,
      "name": "Old Navy",
      "description": "Clothing",
      "categoryId": "gift-cards",
      "cost": 30,
      "price": 30,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "800Old Navy Gift Card.jpg"
    },
    {
      "id": 801,
      "name": "PH Coffee",
      "description": "CafÃ©",
      "categoryId": "gift-cards",
      "cost": 15,
      "price": 15,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "801PH Coffee Gift card.png"
    },
    {
      "id": 802,
      "name": "Subway",
      "description": "Sandwich Resturant",
      "categoryId": "gift-cards",
      "cost": 15,
      "price": 15,
      "ageRange": "6-18",
      "minAge": 6,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "802Subway Gift Card.png"
    },
    {
      "id": 803,
      "name": "Chipotle",
      "description": "American Mexican Resturant",
      "categoryId": "gift-cards",
      "cost": 20,
      "price": 20,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "803Chipotle Gift Card.jpg"
    },
    {
      "id": 804,
      "name": "TJ Maxx",
      "description": "Clothing",
      "categoryId": "gift-cards",
      "cost": 50,
      "price": 50,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "804TJ Maxx Gfit Card.jpg"
    },
    {
      "id": 805,
      "name": "Sky Zone",
      "description": "Trampoline Activities",
      "categoryId": "gift-cards",
      "cost": 25,
      "price": 25,
      "ageRange": "6-18",
      "minAge": 6,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "805Sky Zone Gift Card.webp"
    },
    {
      "id": 806,
      "name": "Cici's",
      "description": "Pizza Resturant",
      "categoryId": "gift-cards",
      "cost": 25,
      "price": 25,
      "ageRange": "6-18",
      "minAge": 6,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "806Cici's Pizza Gift Card.png"
    },
    {
      "id": 807,
      "name": "Ulta",
      "description": "Beauty Asthetic Store",
      "categoryId": "gift-cards",
      "cost": 15,
      "price": 15,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "807Ulta Gift card.jpg"
    },
    {
      "id": 808,
      "name": "QuikTrip",
      "description": "Conveince Store",
      "categoryId": "gift-cards",
      "cost": 25,
      "price": 25,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "808QuikTrip Gift card.jpg"
    },
    {
      "id": 809,
      "name": "Little Caesar's",
      "description": "Pizza Resturant",
      "categoryId": "gift-cards",
      "cost": 30,
      "price": 30,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "809Little Caesar's Pizza Gift Card.webp"
    },
    {
      "id": 810,
      "name": "Fritz's",
      "description": "American Burger Resturant",
      "categoryId": "gift-cards",
      "cost": 30,
      "price": 30,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "810Fritz's Gift Card.webp"
    },
    {
      "id": 811,
      "name": "Yogurtini",
      "description": "Self Serve Resturant",
      "categoryId": "gift-cards",
      "cost": 15,
      "price": 15,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "811Yogurtini Gift Card.png"
    },
    {
      "id": 812,
      "name": "Dairy Queen",
      "description": "American Food and Ice Cream",
      "categoryId": "gift-cards",
      "cost": 20,
      "price": 20,
      "ageRange": "1-18",
      "minAge": 1,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "812Dairy Queen Gift Card.jpg"
    },
    {
      "id": 813,
      "name": "Pizza Street",
      "description": "Pizza Resturant",
      "categoryId": "gift-cards",
      "cost": 10,
      "price": 10,
      "ageRange": "3-9",
      "minAge": 3,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "813Pizza Street Gift Card 9-under.jpg"
    },
    {
      "id": 814,
      "name": "Pizza Street",
      "description": "Pizza Resturant",
      "categoryId": "gift-cards",
      "cost": 22,
      "price": 22,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "814Pizza Street Gift Card 10-Over.jpg"
    },
    {
      "id": 815,
      "name": "Nut Allergy Gift Card",
      "description": "Nut Allergy",
      "categoryId": "gift-cards",
      "cost": 22,
      "price": 22,
      "ageRange": "3-18",
      "minAge": 3,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "815Nut Allergy Needs Gift Card.jpg"
    }
  ],
  "jewelry":   [
    {
      "id": 500,
      "name": "Beaded Bracelet",
      "description": "12pcs Beaded Friendship Bracelets",
      "categoryId": "jewelry",
      "cost": 7,
      "price": 7,
      "ageRange": "11-18",
      "minAge": 11,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "500Beaded Bracelet.jpg"
    },
    {
      "id": 501,
      "name": "Good Vibes Necklace",
      "description": "21\" silver chain.",
      "categoryId": "jewelry",
      "cost": 6,
      "price": 6,
      "ageRange": "12-18",
      "minAge": 12,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "501Good Vibes Necklace.jpg"
    },
    {
      "id": 502,
      "name": "Initial Necklace",
      "description": "18\" Hypoallergenic.",
      "categoryId": "jewelry",
      "cost": 9,
      "price": 9,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "502Initial Necklace.webp"
    },
    {
      "id": 503,
      "name": "Layered necklace",
      "description": "Layered Necklace",
      "categoryId": "jewelry",
      "cost": 16,
      "price": 16,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "503Layered necklace.jpg"
    },
    {
      "id": 504,
      "name": "Leather Bracelet",
      "description": "Leather cuffed Adjustable",
      "categoryId": "jewelry",
      "cost": 10,
      "price": 10,
      "ageRange": "15-18",
      "minAge": 15,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "504Leather Bracelet.jpg"
    },
    {
      "id": 505,
      "name": "Leather Wrap Bracelets",
      "description": "Double Hearts Infinity",
      "categoryId": "jewelry",
      "cost": 5,
      "price": 5,
      "ageRange": "11-18",
      "minAge": 11,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "505Leather Wrap Bracelets.jpg"
    },
    {
      "id": 506,
      "name": "Multilayer Bracelet",
      "description": "Gender neutral beaded hemp cords",
      "categoryId": "jewelry",
      "cost": 6,
      "price": 6,
      "ageRange": "12-18",
      "minAge": 12,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "506Multilayer Bracelet.jpg"
    },
    {
      "id": 507,
      "name": "Tree of Life Bracelets",
      "description": "Leather Tree of life Bracelets",
      "categoryId": "jewelry",
      "cost": 10,
      "price": 10,
      "ageRange": "14-18",
      "minAge": 14,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "507Tree of Life Bracelets.jpg"
    },
    {
      "id": 508,
      "name": "Twisted Rope Chain",
      "description": "Rope Chains - 16\"-30\"",
      "categoryId": "jewelry",
      "cost": 21,
      "price": 21,
      "ageRange": "15-18",
      "minAge": 15,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "508Twisted Rope Chain.jpg"
    }
  ],
  "misc":   [
    {
      "id": 700,
      "name": "Break Open Geode",
      "description": "10 crystal filled geodes. Includes safety goggles.",
      "categoryId": "misc",
      "cost": 12,
      "price": 12,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "700Break Open Geode.jpg"
    },
    {
      "id": 701,
      "name": "Color Changing Cup",
      "description": "6-pack, Lids and Straws",
      "categoryId": "misc",
      "cost": 13,
      "price": 13,
      "ageRange": "5-8",
      "minAge": 5,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "701Color Changing Cup.jpg"
    },
    {
      "id": 702,
      "name": "Croc Charms",
      "description": "25 Croc Charms",
      "categoryId": "misc",
      "cost": 6,
      "price": 6,
      "ageRange": "5-18",
      "minAge": 5,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "702Croc Charms.jpg"
    },
    {
      "id": 703,
      "name": "Crossbody Backback",
      "description": "Carry All the Essentials",
      "categoryId": "misc",
      "cost": 17,
      "price": 17,
      "ageRange": "12-18",
      "minAge": 12,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "703Crossbody Backback.jpg"
    },
    {
      "id": 704,
      "name": "Personalized Blanket",
      "description": "Personalized Blanket",
      "categoryId": "misc",
      "cost": 50,
      "price": 50,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "704Personalized Blanket.webp"
    },
    {
      "id": 705,
      "name": "Shark Hooded Baby Towel",
      "description": "100% cotton towel.",
      "categoryId": "misc",
      "cost": 17,
      "price": 17,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "705Shark Hooded Baby Towel.png"
    },
    {
      "id": 706,
      "name": "Thermos Sports Jug",
      "description": "Half Gallon",
      "categoryId": "misc",
      "cost": 14,
      "price": 14,
      "ageRange": "10-18",
      "minAge": 10,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "706Thermos Sports Jug.jpg"
    },
    {
      "id": 707,
      "name": "Towels",
      "description": "Hooded Bath Blanket. Selection will vary.",
      "categoryId": "misc",
      "cost": 26,
      "price": 26,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "707Towels.jpg"
    },
    {
      "id": 708,
      "name": "Water Bottle for kids",
      "description": "12 oz Stainless Steel",
      "categoryId": "misc",
      "cost": 10,
      "price": 10,
      "ageRange": "2-8",
      "minAge": 2,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "708Water Bottle for kids.jpg"
    },
    {
      "id": 709,
      "name": "Water Cup - Large",
      "description": "40 oz insulated, handle",
      "categoryId": "misc",
      "cost": 15,
      "price": 15,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "709Water Cup - Large.jpg"
    },
    {
      "id": 710,
      "name": "Water Cup - Medium",
      "description": "20 oz insulated, handle",
      "categoryId": "misc",
      "cost": 12,
      "price": 12,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "710Water Cup - Medium.jpg"
    },
    {
      "id": 711,
      "name": "White Fuzzy Rug",
      "description": "4x6",
      "categoryId": "misc",
      "cost": 35,
      "price": 35,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "711White Fuzzy Rug.jpg"
    },
    {
      "id": 712,
      "name": "It's my Birthday Pin",
      "description": "Fun pin to wear on your birthday. Selection varies.",
      "categoryId": "misc",
      "cost": 5,
      "price": 3,
      "ageRange": "3-18",
      "minAge": 3,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "712Its My Birthday Pin.jpg"
    }
  ],
  "sports":   [
    {
      "id": 600,
      "name": "Balls for Toddler",
      "description": "Foam play sports balls",
      "categoryId": "sports",
      "cost": 25,
      "price": 20,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "600Balls for Toddler .png"
    },
    {
      "id": 601,
      "name": "Baseball 3 in 1 Set for Kids 3-5 Adjustable Height",
      "description": "Tee Ball Stand, Hanging Tee, Ball Launcher and 6 Softballs",
      "categoryId": "sports",
      "cost": 15,
      "price": 24,
      "ageRange": "2-3",
      "minAge": 2,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "601Baseball 3 in 1 Set for Kids 3-5 - Tee Ball Stand, Hanging Tee, Ball Launcher and 6 Softballs - Adjustable Height.jpg"
    },
    {
      "id": 602,
      "name": "Basketball",
      "description": "Orange -Size 7 (29.5\")",
      "categoryId": "sports",
      "cost": 13,
      "price": 13,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "602Basketball.jpg"
    },
    {
      "id": 603,
      "name": "Basketball Kids",
      "description": "Orange - Size 5 (27.5\")",
      "categoryId": "sports",
      "cost": 13,
      "price": 13,
      "ageRange": "10-12",
      "minAge": 10,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "603Basketball Kids.jpg"
    },
    {
      "id": 604,
      "name": "Basketball Youth",
      "description": "Orange - size 3 (23\")",
      "categoryId": "sports",
      "cost": 10,
      "price": 10,
      "ageRange": "4-9",
      "minAge": 4,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "604Basketball Youth.jpg"
    },
    {
      "id": 605,
      "name": "Double Jump Rope",
      "description": "16 feet",
      "categoryId": "sports",
      "cost": 16,
      "price": 16,
      "ageRange": "6-18",
      "minAge": 6,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "605Double Jump Rope.png"
    },
    {
      "id": 606,
      "name": "Fishing Rod and Reel Combo",
      "description": "34\" fishing rod & reel. Includes safety hook.",
      "categoryId": "sports",
      "cost": 25,
      "price": 25,
      "ageRange": "6-18",
      "minAge": 6,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "606Fishing Rod and Reel Combo.jpg"
    },
    {
      "id": 607,
      "name": "Football",
      "description": "Football",
      "categoryId": "sports",
      "cost": 15,
      "price": 15,
      "ageRange": "8-12",
      "minAge": 8,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "607Football.jpg"
    },
    {
      "id": 608,
      "name": "Footbal - Chiefs",
      "description": "Chiefs! Junior 8.5\"",
      "categoryId": "sports",
      "cost": 15,
      "price": 15,
      "ageRange": "5-9",
      "minAge": 5,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "608Footbal - Chiefs.jpg"
    },
    {
      "id": 609,
      "name": "Footbal Kicking Tee",
      "description": "Size 1\" standard football kick-off kicking tee",
      "categoryId": "sports",
      "cost": 5,
      "price": 5,
      "ageRange": "6-18",
      "minAge": 6,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "609Footbal Kicking Tee.jpg"
    },
    {
      "id": 610,
      "name": "Football Youth",
      "description": "Youth size",
      "categoryId": "sports",
      "cost": 12,
      "price": 14,
      "ageRange": "6-11",
      "minAge": 6,
      "maxAge": 11,
      "ageGroup": "5to12",
      "image": "610Football Youth.jpg"
    },
    {
      "id": 611,
      "name": "L.O.L. Surprise! Quad Adjustable Roller Skate",
      "description": "Easy beginner skates. Recommended for a shoe size of 10-13",
      "categoryId": "sports",
      "cost": 40,
      "price": 40,
      "ageRange": "4-6",
      "minAge": 4,
      "maxAge": 6,
      "ageGroup": "5to12",
      "image": "611L.O.L. Surprise! Quad Adjustable Roller Skate.png"
    },
    {
      "id": 612,
      "name": "Mini Basketball Hoop",
      "description": "Over the door mount",
      "categoryId": "sports",
      "cost": 35,
      "price": 35,
      "ageRange": "6-18",
      "minAge": 6,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "612Mini Basketball Hoop.jpg"
    },
    {
      "id": 613,
      "name": "Pro Vision 31 Skateboard",
      "description": "Fully assembled with grip-tape and skate hardware.",
      "categoryId": "sports",
      "cost": 40,
      "price": 40,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "613Pro Vision 31 Skateboard.jpg"
    },
    {
      "id": 614,
      "name": "Punt, Pass And Shoot Ball Set",
      "description": "Baseball, basketball, soccer ball, and football set.",
      "categoryId": "sports",
      "cost": 14,
      "price": 14,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "614Punt, Pass And Shoot Ball Set.webp"
    },
    {
      "id": 615,
      "name": "Push & Pop Bulldozer",
      "description": "Pop! Pop! Pop!",
      "categoryId": "sports",
      "cost": 25,
      "price": 25,
      "ageRange": "2-4",
      "minAge": 2,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "615ush & Pop Bulldozer.jpg"
    },
    {
      "id": 616,
      "name": "Razor A Kick Scooter",
      "description": "Classic scooter,Lightweight,Folds easily",
      "categoryId": "sports",
      "cost": 30,
      "price": 30,
      "ageRange": "5-12",
      "minAge": 5,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "616Razor A Kick Scooter.png"
    },
    {
      "id": 617,
      "name": "Single Jump Rope",
      "description": "8 ft Jump rope",
      "categoryId": "sports",
      "cost": 10,
      "price": 10,
      "ageRange": "5-18",
      "minAge": 5,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "617Single Jump Rope.png"
    },
    {
      "id": 618,
      "name": "Soccer Ball",
      "description": "Kickball",
      "categoryId": "sports",
      "cost": 19,
      "price": 15,
      "ageRange": "13-15",
      "minAge": 13,
      "maxAge": 15,
      "ageGroup": "12plus",
      "image": "618Soccer Ball.jpg"
    },
    {
      "id": 619,
      "name": "Soccer Ball - youth",
      "description": "Kickball",
      "categoryId": "sports",
      "cost": 15,
      "price": 15,
      "ageRange": "8-12",
      "minAge": 8,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "619Soccer Ball - youth.jpg"
    },
    {
      "id": 620,
      "name": "Sonic Fin Football",
      "description": "Aerodynamic toy",
      "categoryId": "sports",
      "cost": 15,
      "price": 15,
      "ageRange": "6-12",
      "minAge": 6,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "620Sonic Fin Football.jpg"
    },
    {
      "id": 621,
      "name": "Youth Inline Skate",
      "description": "Adjustable Fit, Gliding Action",
      "categoryId": "sports",
      "cost": 38,
      "price": 38,
      "ageRange": "7-10",
      "minAge": 7,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "621Youth Inline Skate.png"
    }
  ],
  "sweet-treats":   [
    {
      "id": 1000,
      "name": "HB",
      "description": "Happy Birthday!",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "1000HB.jpg"
    },
    {
      "id": 1001,
      "name": "HB",
      "description": "Happy Birthday!",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "1001HB.jpg"
    },
    {
      "id": 1002,
      "name": "HB",
      "description": "Happy Birthday!",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "1002HB.jpg"
    },
    {
      "id": 1003,
      "name": "HB",
      "description": "Happy Birthday!",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "1003HB.jpg"
    },
    {
      "id": 1004,
      "name": "HB",
      "description": "Happy Birthday!",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "1004HB.jpg"
    },
    {
      "id": 1005,
      "name": "HB",
      "description": "Happy Birthday!",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "1005HB.jpg"
    },
    {
      "id": 2000,
      "name": "CC Cookie Cake & Vanilla Frosting",
      "description": "Cake",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2000CC Cookie Cake & Vanilla Frosting.jpeg"
    },
    {
      "id": 2001,
      "name": "CC Cookie Cake & Chocolate Frosting",
      "description": "Cake",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2001CC Cookie Cake Chocolate Frosting.jpeg"
    },
    {
      "id": 2002,
      "name": "Chocolate Cake Chocolate Frosting",
      "description": "Cake",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2002Chocolate Cake Chocolate Frosting.jpeg"
    },
    {
      "id": 2003,
      "name": "Chocolate Cake Vanilla Frosting",
      "description": "Cake",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2003Chocolate Cake Vanilla Frosting.jpeg"
    },
    {
      "id": 2004,
      "name": "Chocolate Chip cookie",
      "description": "Cookie",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2004Chocolate Chip Cookie Cake.jpeg"
    },
    {
      "id": 2005,
      "name": "Cookies Browine",
      "description": "Brownie",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2005Cookies-Brownie.jpeg"
    },
    {
      "id": 2006,
      "name": "Cookies Chocolate Chip",
      "description": "Cookie",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2006Cookies-Chocolate Chip.jpeg"
    },
    {
      "id": 2007,
      "name": "Cookies Sugar",
      "description": "Cookie",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2007Cookies Sugar.jpeg"
    },
    {
      "id": 2008,
      "name": "Dairy Free Cake Vanilla Frosting",
      "description": "Cake",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2008Dairy Free Cake Vanilla Frosting.jpeg"
    },
    {
      "id": 2009,
      "name": "Marble Cake Chocolate Frosting",
      "description": "Cake",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2009Marble Cake & Chocolate Frosting.jpeg"
    },
    {
      "id": 2010,
      "name": "Marble Cake Vanilla Frosting",
      "description": "Cake",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2010Marble Cake & Vanilla Frosting.jpeg"
    },
    {
      "id": 2011,
      "name": "White Cake Chocolate Frosting",
      "description": "Cake",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2011White Cake Chocolate Frosting.jpeg"
    },
    {
      "id": 2012,
      "name": "White Cake Vanilla Frosting",
      "description": "Cake",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2012White Cake Vanilla Frosting.jpeg"
    },
    {
      "id": 2013,
      "name": "Cookies M&M",
      "description": "Cookie",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "2013Cookies-M&M.jpeg"
    },
    {
      "id": 3000,
      "name": "Paper Streamers",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3000Paper Streamers.png"
    },
    {
      "id": 3001,
      "name": "Candles",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3001Candles.png"
    },
    {
      "id": 3002,
      "name": "Scissors",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3002Scissors.png"
    },
    {
      "id": 3003,
      "name": "Tape",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3003Tape.png"
    },
    {
      "id": 3004,
      "name": "Gift Bag",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3004Gift bag 16White.png"
    },
    {
      "id": 3005,
      "name": "Gift Bag",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3005Gift Bag 13White.png"
    },
    {
      "id": 3006,
      "name": "Candle Bag",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3006Candle Bag 3 4.png"
    },
    {
      "id": 3007,
      "name": "Gift Bag",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3007Gift Bag 13Blue.png"
    },
    {
      "id": 3008,
      "name": "Gift Bag",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3008Candle Bag 3 4.png"
    },
    {
      "id": 3009,
      "name": "Candle Bag",
      "description": "Supplies",
      "categoryId": "sweet-treats",
      "cost": 0,
      "price": 0,
      "ageRange": null,
      "minAge": null,
      "maxAge": null,
      "ageGroup": null,
      "image": "3009Candle Bag 2 3.png"
    }
  ],
  "toys":   [
    {
      "id": 101,
      "name": "Alaphabet Express",
      "description": "28 Piece alphabet floor puzzle",
      "categoryId": "toys",
      "cost": 5,
      "price": 5,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "101Alaphabet Express.jpg"
    },
    {
      "id": 102,
      "name": "Baby's First Blocks",
      "description": "10 Shapes for sorting",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "102Baby's First Blocks.jpg"
    },
    {
      "id": 103,
      "name": "Baby Multi-Sensory Blocks",
      "description": "ABC, Animals, Colors",
      "categoryId": "toys",
      "cost": 15,
      "price": 15,
      "ageRange": "1-5",
      "minAge": 1,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "103Baby Multi-sensory Blocks.jpg"
    },
    {
      "id": 104,
      "name": "Binoculars",
      "description": "Includes a neck strap",
      "categoryId": "toys",
      "cost": 12,
      "price": 12,
      "ageRange": "6-9",
      "minAge": 6,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "104Binoculars.jpg"
    },
    {
      "id": 105,
      "name": "Blanket - Funny Pizza",
      "description": "Flannel",
      "categoryId": "toys",
      "cost": 30,
      "price": 30,
      "ageRange": "5-18",
      "minAge": 5,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "105Blanket Funny Pizza.jpg"
    },
    {
      "id": 106,
      "name": "Buddy the Cat Ride-on",
      "description": "Handle to give a helping hand.",
      "categoryId": "toys",
      "cost": 26,
      "price": 26,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "106Buddy the Cat Ride-on.jpg"
    },
    {
      "id": 107,
      "name": "Bug Viewer,Catcher, & Magnifier",
      "description": "Butterfly net, observation jar, insect collection box, tweezers, magnifying glass.",
      "categoryId": "toys",
      "cost": 18,
      "price": 18,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "107Bug Viewer,Catcher, & Magnifier .jpg"
    },
    {
      "id": 108,
      "name": "Burger and Fries",
      "description": "Stress reliever fidget.",
      "categoryId": "toys",
      "cost": 7,
      "price": 7,
      "ageRange": "2-18",
      "minAge": 2,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "108Burger and Fries.jpg"
    },
    {
      "id": 109,
      "name": "Calico Cat Warmie",
      "description": "Microwave or freezer for stress relief, reduce anxiety",
      "categoryId": "toys",
      "cost": 25,
      "price": 25,
      "ageRange": "3-13",
      "minAge": 3,
      "maxAge": 13,
      "ageGroup": "5to12",
      "image": "109Calico Cat Warmie.png"
    },
    {
      "id": 110,
      "name": "Carpenter Dress Up Set",
      "description": "Dress construction worker.",
      "categoryId": "toys",
      "cost": 22,
      "price": 22,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "110Carpenter Dress Up Set.webp"
    },
    {
      "id": 111,
      "name": "Caterpillar Xylophone",
      "description": "Music fun! Wooden",
      "categoryId": "toys",
      "cost": 11,
      "price": 11,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "111Caterpillar Xylophone.jpg"
    },
    {
      "id": 112,
      "name": "Clean Up Set",
      "description": "Cleaning set.",
      "categoryId": "toys",
      "cost": 18,
      "price": 18,
      "ageRange": "3-5",
      "minAge": 3,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "112Clean Up Set.jpg"
    },
    {
      "id": 113,
      "name": "Corn Popper",
      "description": "Classic push toy.",
      "categoryId": "toys",
      "cost": 14,
      "price": 14,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "113Corn Popper.jpg"
    },
    {
      "id": 114,
      "name": "Crinkle Toy",
      "description": "Perfect for playing, car seats, and strollers.",
      "categoryId": "toys",
      "cost": 15,
      "price": 15,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "114Crinkle Toy.jpg"
    },
    {
      "id": 115,
      "name": "Dig It Up - Volcano",
      "description": "Volcano surprise! Dig out fascinating artifacts!",
      "categoryId": "toys",
      "cost": 5,
      "price": 5,
      "ageRange": "8-12",
      "minAge": 8,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "115Dig It Up - Volcano.jpeg"
    },
    {
      "id": 116,
      "name": "Dimple Digit",
      "description": "Touch, push, pop. 1 to 10 in English and Spanish.",
      "categoryId": "toys",
      "cost": 16,
      "price": 16,
      "ageRange": "3-5",
      "minAge": 3,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "116Dimple Digit.jpg"
    },
    {
      "id": 117,
      "name": "Dishwashing Fun Set",
      "description": "Play washing dishes. CHOKING HAZARD: Small parts. Not for children under 3 years.",
      "categoryId": "toys",
      "cost": 15,
      "price": 15,
      "ageRange": "4-6",
      "minAge": 4,
      "maxAge": 6,
      "ageGroup": "5to12",
      "image": "117Dishwashing Fun Set.jpg"
    },
    {
      "id": 118,
      "name": "Easy Grasp Ball",
      "description": "Classic toy!",
      "categoryId": "toys",
      "cost": 5,
      "price": 5,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "118Easy Grasp Ball.jpg"
    },
    {
      "id": 119,
      "name": "Floor Piano Playmat",
      "description": "Step on Musical Floor Mat",
      "categoryId": "toys",
      "cost": 26,
      "price": 26,
      "ageRange": "2-6",
      "minAge": 2,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "119Floor Piano Playmat.jpg"
    },
    {
      "id": 120,
      "name": "Golden Dog Warmies",
      "description": "13\". Microwave or freezer for stress relief, reduce anxiety. Lavender.",
      "categoryId": "toys",
      "cost": 21,
      "price": 21,
      "ageRange": "3-18",
      "minAge": 3,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "120Golden Dog Warmies.png"
    },
    {
      "id": 121,
      "name": "Johnny Jungle Plane",
      "description": "Friction-powered",
      "categoryId": "toys",
      "cost": 33,
      "price": 33,
      "ageRange": "1-4",
      "minAge": 1,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "121Johnny Jungle Plane.jpeg"
    },
    {
      "id": 122,
      "name": "Jungle Maracas Egg Shakers",
      "description": "3-piece set.",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "122Jungle Maracas Egg Shakers.jpg"
    },
    {
      "id": 123,
      "name": "Karaoke Microphone",
      "description": "Bluetooth karaoke microphone with speaker.",
      "categoryId": "toys",
      "cost": 20,
      "price": 20,
      "ageRange": "8-12",
      "minAge": 8,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "123Karaoke Microphone.jpg"
    },
    {
      "id": 124,
      "name": "Kitchen Set",
      "description": "Wooden cooking set.",
      "categoryId": "toys",
      "cost": 25,
      "price": 25,
      "ageRange": "2-3",
      "minAge": 2,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "124Kitchen Set.jpg"
    },
    {
      "id": 125,
      "name": "Kittens",
      "description": "4 miniture kitties",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "6-10",
      "minAge": 6,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "125Kittens.jpg"
    },
    {
      "id": 126,
      "name": "LiquiFly FizzRocket",
      "description": "Launch with baking soda and vinegar.",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "12-18",
      "minAge": 12,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "126LiquiFly FizzRocket.png"
    },
    {
      "id": 127,
      "name": "Magnetic Tiles Toys",
      "description": "40 magnetic building tiles",
      "categoryId": "toys",
      "cost": 36,
      "price": 36,
      "ageRange": "4-9",
      "minAge": 4,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "127Magnetic Tiles Toys.png"
    },
    {
      "id": 128,
      "name": "Makeup & Bag",
      "description": "Cosmetics Set",
      "categoryId": "toys",
      "cost": 20,
      "price": 20,
      "ageRange": "14-16",
      "minAge": 14,
      "maxAge": 16,
      "ageGroup": "12plus",
      "image": "128Makeup & Bag.jpg"
    },
    {
      "id": 129,
      "name": "Make-up Brushes",
      "description": "Makeup Set",
      "categoryId": "toys",
      "cost": 4,
      "price": 4,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "129Make-up Brushes.jpg"
    },
    {
      "id": 130,
      "name": "Makeup Essentials",
      "description": "Makeup Set",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "14-18",
      "minAge": 14,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "130Makeup - Essentials.jpg"
    },
    {
      "id": 131,
      "name": "Marble Run",
      "description": "Create your own design. NOT SUITABLE FOR CHILDREN 3 AND UNDER.",
      "categoryId": "toys",
      "cost": 27,
      "price": 27,
      "ageRange": "6-12",
      "minAge": 6,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "131Marble Run.jpg"
    },
    {
      "id": 132,
      "name": "Marble Tracks Builder Set",
      "description": "Create your own design. NOT SUITABLE FOR CHILDREN 3 AND UNDER.",
      "categoryId": "toys",
      "cost": 23,
      "price": 23,
      "ageRange": "8-10",
      "minAge": 8,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "132Marble Tracks Builder Set.jpg"
    },
    {
      "id": 133,
      "name": "Math Dice",
      "description": "Math game.",
      "categoryId": "toys",
      "cost": 11,
      "price": 11,
      "ageRange": "9-16",
      "minAge": 9,
      "maxAge": 16,
      "ageGroup": "12plus",
      "image": "133Math Dice.jpg"
    },
    {
      "id": 134,
      "name": "Mega Blocks",
      "description": "80 blocks",
      "categoryId": "toys",
      "cost": 24,
      "price": 24,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "134MegaBlocks.jpg"
    },
    {
      "id": 135,
      "name": "Mr. Potato Head",
      "description": "Classic!",
      "categoryId": "toys",
      "cost": 8,
      "price": 8,
      "ageRange": "3-8",
      "minAge": 3,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "135Mr. Potato Head.jpg"
    },
    {
      "id": 136,
      "name": "Musical Toy",
      "description": "Sensory Learning Music",
      "categoryId": "toys",
      "cost": 7,
      "price": 7,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "136Musical Toy.jpg"
    },
    {
      "id": 137,
      "name": "Music Parade Ride-On",
      "description": "Cool ride and musical fun!",
      "categoryId": "toys",
      "cost": 50,
      "price": 50,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "137Music Parade Ride-On.png"
    },
    {
      "id": 138,
      "name": "My Toolbox",
      "description": "Describes how a house is built.",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "1-5",
      "minAge": 1,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "138My Toolbox.jpg"
    },
    {
      "id": 139,
      "name": "Picnic Set",
      "description": "Stimulate Picnic Experience with toys",
      "categoryId": "toys",
      "cost": 22,
      "price": 22,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "139Picnic Set.jpg"
    },
    {
      "id": 140,
      "name": "Play Tunnel",
      "description": "Colorful!",
      "categoryId": "toys",
      "cost": 20,
      "price": 20,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "140Play Tunnel.jpg"
    },
    {
      "id": 141,
      "name": "Pop-its 100",
      "description": "Fidget with numbers up to 100",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "4-10",
      "minAge": 4,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "141Pop-its 100.jpg"
    },
    {
      "id": 142,
      "name": "Pop its 1-100",
      "description": "Fidget with numbers up to 100",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "4-10",
      "minAge": 4,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "142Pop its 1-100.jpg"
    },
    {
      "id": 143,
      "name": "Pop-Its Fidgets",
      "description": "Colors vary.",
      "categoryId": "toys",
      "cost": 3,
      "price": 3,
      "ageRange": "4-10",
      "minAge": 4,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "143Pop-Its Fidgets.jpg"
    },
    {
      "id": 144,
      "name": "Pound-A-Ball Toy",
      "description": "Wooden 4-wheel car, pound a ball, and shape sorter.",
      "categoryId": "toys",
      "cost": 23,
      "price": 23,
      "ageRange": "2-3",
      "minAge": 2,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "144Pound-A-Ball Toy.jpg"
    },
    {
      "id": 145,
      "name": "Princess Tent",
      "description": "Indoor and outdoor. Star Lights included. 55'' x 53''",
      "categoryId": "toys",
      "cost": 37,
      "price": 37,
      "ageRange": "4-7",
      "minAge": 4,
      "maxAge": 7,
      "ageGroup": "5to12",
      "image": "145Princess Tent.png"
    },
    {
      "id": 146,
      "name": "Ring Spinners",
      "description": "Magnetic Fidget",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "9-18",
      "minAge": 9,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "146Ring Spinners.jpg"
    },
    {
      "id": 147,
      "name": "Rock n' Roller Piano",
      "description": "Melody-making fun!",
      "categoryId": "toys",
      "cost": 30,
      "price": 30,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "147Rock n' Roller Piano.webp"
    },
    {
      "id": 148,
      "name": "Rocking Horse",
      "description": "Learn balance and coordination.",
      "categoryId": "toys",
      "cost": 35,
      "price": 35,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "148Rocking Horse .jpg"
    },
    {
      "id": 149,
      "name": "Rubber Ball",
      "description": "9-inch rubber kickball.",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "2-10",
      "minAge": 2,
      "maxAge": 10,
      "ageGroup": "5to12",
      "image": "149Rubber Ball.jpg"
    },
    {
      "id": 150,
      "name": "Rubber Pop Up Toys",
      "description": "Flips inside out and back.",
      "categoryId": "toys",
      "cost": 12,
      "price": 12,
      "ageRange": "3-7",
      "minAge": 3,
      "maxAge": 7,
      "ageGroup": "5to12",
      "image": "150Rubber Pop Up Toys.jpg"
    },
    {
      "id": 151,
      "name": "Rubik's Cube",
      "description": "Classic solve the cube",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "8-15",
      "minAge": 8,
      "maxAge": 15,
      "ageGroup": "5to12",
      "image": "151Rubik's Cube.jpg"
    },
    {
      "id": 152,
      "name": "Sensory Strings - 6 pack",
      "description": "6 pack. Stress relief. Visual stimulation.",
      "categoryId": "toys",
      "cost": 12,
      "price": 12,
      "ageRange": "6-18",
      "minAge": 6,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "152Sensory Strings - 6 pack.jpg"
    },
    {
      "id": 153,
      "name": "Sit â€˜n Spin",
      "description": "Sit, spin, and giggle yourself silly.",
      "categoryId": "toys",
      "cost": 35,
      "price": 35,
      "ageRange": "2-5",
      "minAge": 2,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "153Sit ‘n Spin .png"
    },
    {
      "id": 154,
      "name": "Slide for Toddlers",
      "description": "Safe for younger kids. Indoor and outdoors use.",
      "categoryId": "toys",
      "cost": 25,
      "price": 25,
      "ageRange": "2-3",
      "minAge": 2,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "154Slide for Toddlers.jpg"
    },
    {
      "id": 155,
      "name": "Slinky",
      "description": "Classic spring walking toy.",
      "categoryId": "toys",
      "cost": 4,
      "price": 4,
      "ageRange": "5-18",
      "minAge": 5,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "155Slinky.jpg"
    },
    {
      "id": 156,
      "name": "Snow Beauty",
      "description": "Frozen Theme Tea Set",
      "categoryId": "toys",
      "cost": 28,
      "price": 28,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "156Snow Beauty.jpg"
    },
    {
      "id": 157,
      "name": "Spa Kit",
      "description": "Inflatable tub DIY Manicure/Pedicure",
      "categoryId": "toys",
      "cost": 25,
      "price": 25,
      "ageRange": "6-9",
      "minAge": 6,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "157Spa Kit.jpg"
    },
    {
      "id": 158,
      "name": "Spike the Hedgehog",
      "description": "Fine motor and sensory learning.",
      "categoryId": "toys",
      "cost": 14,
      "price": 14,
      "ageRange": "2-4",
      "minAge": 2,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "158Spike the Hedgehog.jpg"
    },
    {
      "id": 159,
      "name": "Stack and Count Cups",
      "description": "8 cups",
      "categoryId": "toys",
      "cost": 8,
      "price": 8,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "159Stack and Count Cups.jpg"
    },
    {
      "id": 160,
      "name": "Stuffed Animal - Dog",
      "description": "10' plush",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "1-18",
      "minAge": 1,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "160Stuffed Animal - Dog.jpg"
    },
    {
      "id": 161,
      "name": "Stuffed Animal - Hamburger Bear",
      "description": "Happy Birthday!",
      "categoryId": "toys",
      "cost": 11,
      "price": 11,
      "ageRange": "1-18",
      "minAge": 1,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "161Stuffed Animal - Hamburger Bear.jpg"
    },
    {
      "id": 162,
      "name": "Stuffed Animal - Hedgehog",
      "description": "10\" plush",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "1-18",
      "minAge": 1,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "162Stuffed Animal - Hedgehog.jpg"
    },
    {
      "id": 163,
      "name": "Stuffed Animal - Unicorn Cat",
      "description": "Happy Birthday!",
      "categoryId": "toys",
      "cost": 12,
      "price": 12,
      "ageRange": "1-18",
      "minAge": 1,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "163Stuffed Animal - Unicorn Cat.jpg"
    },
    {
      "id": 164,
      "name": "Super Heroes - Action Figures",
      "description": "5 Super Hero Action Heroes",
      "categoryId": "toys",
      "cost": 12,
      "price": 12,
      "ageRange": "5-14",
      "minAge": 5,
      "maxAge": 14,
      "ageGroup": "5to12",
      "image": "164Super Heroes - Action Figures.jpg"
    },
    {
      "id": 165,
      "name": "Tea Party Set",
      "description": "With Play food",
      "categoryId": "toys",
      "cost": 15,
      "price": 15,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "165Tea Party Set.jpg"
    },
    {
      "id": 166,
      "name": "Thinking Putty - Mixed Emotions",
      "description": "Emojis Stretchy putty",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "3-18",
      "minAge": 3,
      "maxAge": 18,
      "ageGroup": "5to12",
      "image": "166Thinking Putty - Mixed Emotions.png"
    },
    {
      "id": 167,
      "name": "Toddler Bike",
      "description": "Colorful wooden bike!",
      "categoryId": "toys",
      "cost": 40,
      "price": 40,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "167Toddler Bike.webp"
    },
    {
      "id": 168,
      "name": "Transformable Spinner",
      "description": "Fidget Spinners",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "168Transformable Spinner.jpg"
    },
    {
      "id": 169,
      "name": "Unicorn Tea Set",
      "description": "Tea Set Magical Unicorns, Rainbows and Stars",
      "categoryId": "toys",
      "cost": 28,
      "price": 28,
      "ageRange": "3-8",
      "minAge": 3,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "169Unicorn Tea Set.jpg"
    },
    {
      "id": 170,
      "name": "Voice Changer",
      "description": "Megaphone + 5 different voice sound effects.",
      "categoryId": "toys",
      "cost": 20,
      "price": 20,
      "ageRange": "1-8",
      "minAge": 1,
      "maxAge": 8,
      "ageGroup": "under5",
      "image": "170Warmie Bear.jpg"
    },
    {
      "id": 171,
      "name": "Warmie Bear",
      "description": "Microwavable to warm.",
      "categoryId": "toys",
      "cost": 20,
      "price": 20,
      "ageRange": "1-2",
      "minAge": 1,
      "maxAge": 2,
      "ageGroup": "under5",
      "image": "171Whirl'n Go Ball Tower Kidoozie.jpg"
    },
    {
      "id": 172,
      "name": "Whirl'n Go Ball Tower Kidoozie",
      "description": "Development toy Stacked level",
      "categoryId": "toys",
      "cost": 20,
      "price": 20,
      "ageRange": "1-4",
      "minAge": 1,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "172Voice Changer.jpg"
    },
    {
      "id": 173,
      "name": "Wood Blocks",
      "description": "50 block set.",
      "categoryId": "toys",
      "cost": 22,
      "price": 22,
      "ageRange": "2-3",
      "minAge": 2,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "173Wood Blocks.jpg"
    },
    {
      "id": 174,
      "name": "Wooden Bee Ride-on",
      "description": "Made with natural wood.",
      "categoryId": "toys",
      "cost": 32,
      "price": 32,
      "ageRange": "1-4",
      "minAge": 1,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "174Wooden Bee Ride-on.jpg"
    },
    {
      "id": 175,
      "name": "Wooden Stacking Rings",
      "description": "Rainbow colors.",
      "categoryId": "toys",
      "cost": 11,
      "price": 11,
      "ageRange": "9-18",
      "minAge": 9,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "175Wooden Stacking Rings.jpg"
    },
    {
      "id": 176,
      "name": "Yo yo",
      "description": "Colors vary.",
      "categoryId": "toys",
      "cost": 5,
      "price": 5,
      "ageRange": "1-5",
      "minAge": 1,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "176Yo yo.jpg"
    },
    {
      "id": 177,
      "name": "Black Boy Doll",
      "description": "14\" dark skin tone.",
      "categoryId": "toys",
      "cost": 17,
      "price": 17,
      "ageRange": "1-8",
      "minAge": 1,
      "maxAge": 8,
      "ageGroup": "under5",
      "image": "177Black Boy Doll.webp"
    },
    {
      "id": 178,
      "name": "Boy Doll",
      "description": "14\" plush doll",
      "categoryId": "toys",
      "cost": 17,
      "price": 17,
      "ageRange": "1-8",
      "minAge": 1,
      "maxAge": 8,
      "ageGroup": "under5",
      "image": "178Boy Doll.jpg"
    },
    {
      "id": 179,
      "name": "Doll Girl",
      "description": "14\" plush doll.",
      "categoryId": "toys",
      "cost": 17,
      "price": 17,
      "ageRange": "1-5",
      "minAge": 1,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "179Doll Girl.jpg"
    },
    {
      "id": 180,
      "name": "Girl Plush Doll",
      "description": "14\" plush doll",
      "categoryId": "toys",
      "cost": 20,
      "price": 20,
      "ageRange": "3-5",
      "minAge": 3,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "180Girl Plush Doll.jpg"
    },
    {
      "id": 181,
      "name": "La Baby Hispanic Doll",
      "description": "La Baby 20\". Huggable and easy to cuddle.",
      "categoryId": "toys",
      "cost": 30,
      "price": 30,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "181La Baby Hispanic.png"
    },
    {
      "id": 182,
      "name": "Latino Baby Doll",
      "description": "10\" soft",
      "categoryId": "toys",
      "cost": 15,
      "price": 15,
      "ageRange": "4-8",
      "minAge": 4,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "182Latino doll.jpg"
    },
    {
      "id": 183,
      "name": "Soccer Doll",
      "description": "Ken Fashion Doll & Accessory, Soccer Player",
      "categoryId": "toys",
      "cost": 12,
      "price": 12,
      "ageRange": "1-3",
      "minAge": 1,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "183Soccer Doll.jpg"
    },
    {
      "id": 184,
      "name": "Wee Baby Doll",
      "description": "Wee Baby Stella Brown 12\" Soft Baby Doll.",
      "categoryId": "toys",
      "cost": 26,
      "price": 26,
      "ageRange": "1-6",
      "minAge": 1,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "184Wee Baby Doll.jpeg"
    },
    {
      "id": 185,
      "name": "White Baby Doll",
      "description": "8\" plush",
      "categoryId": "toys",
      "cost": 15,
      "price": 15,
      "ageRange": "4-12",
      "minAge": 4,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "185White Baby Doll.jpg"
    },
    {
      "id": 186,
      "name": "Wildlife Photographer Doll",
      "description": "Mia - 7\" doll Photography accessories.",
      "categoryId": "toys",
      "cost": 28,
      "price": 28,
      "ageRange": "2-4",
      "minAge": 2,
      "maxAge": 4,
      "ageGroup": "under5",
      "image": "186WildlifePhotographer.webp"
    },
    {
      "id": 187,
      "name": "Doll Red Dress",
      "description": "14â€ soft sensory fabric",
      "categoryId": "toys",
      "cost": 14,
      "price": 14,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "187Doll Red Dress.jpg"
    },
    {
      "id": 188,
      "name": "Legos Chain Reaction",
      "description": "10 moving machines.",
      "categoryId": "toys",
      "cost": 22,
      "price": 22,
      "ageRange": "7-12",
      "minAge": 7,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "188Legos Chain Reaction.jpg"
    },
    {
      "id": 189,
      "name": "Legos Dino",
      "description": "3 in 1 Dinosaur Lego Set",
      "categoryId": "toys",
      "cost": 15,
      "price": 15,
      "ageRange": "13-18",
      "minAge": 13,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "189Legos Dino.jpg"
    },
    {
      "id": 190,
      "name": "Legos Flower",
      "description": "LEGO Plum Blossoms",
      "categoryId": "toys",
      "cost": 24,
      "price": 24,
      "ageRange": "0-3",
      "minAge": 0,
      "maxAge": 3,
      "ageGroup": "under5",
      "image": "190Legos Flower.jpg"
    },
    {
      "id": 191,
      "name": "Legos Gearbots",
      "description": "LEGO kit - 8 different moving machines.",
      "categoryId": "toys",
      "cost": 25,
      "price": 25,
      "ageRange": "7-12",
      "minAge": 7,
      "maxAge": 12,
      "ageGroup": "5to12",
      "image": "191Legos Gearbots.jpg"
    },
    {
      "id": 192,
      "name": "Lego Set",
      "description": "Deep Sea Creatures.",
      "categoryId": "toys",
      "cost": 15,
      "price": 15,
      "ageRange": "8-18",
      "minAge": 8,
      "maxAge": 18,
      "ageGroup": "12plus",
      "image": "192Lego Set.jpg"
    },
    {
      "id": 193,
      "name": "Lego Spiderman",
      "description": "LEGO Spider-Man Action Figure",
      "categoryId": "toys",
      "cost": 20,
      "price": 20,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "193Lego Spiderman.jpg"
    },
    {
      "id": 194,
      "name": "Construction Trucks",
      "description": "Set of 4",
      "categoryId": "toys",
      "cost": 17,
      "price": 17,
      "ageRange": "3-6",
      "minAge": 3,
      "maxAge": 6,
      "ageGroup": "under5",
      "image": "194Construction Trucks .jpg"
    },
    {
      "id": 195,
      "name": "Emergency Vehicle Carrier",
      "description": "Truck and emergency vehicle toy set.",
      "categoryId": "toys",
      "cost": 16,
      "price": 16,
      "ageRange": "6-9",
      "minAge": 6,
      "maxAge": 9,
      "ageGroup": "5to12",
      "image": "195Emergency Vehicle Carrier.jpg"
    },
    {
      "id": 196,
      "name": "Hot Wheels Track Builder",
      "description": "Gas-can-shaped container holds track pieces + 1 Hot Wheels Car.",
      "categoryId": "toys",
      "cost": 28,
      "price": 28,
      "ageRange": "3-5",
      "minAge": 3,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "196Hot Wheels Track Builder.jpg"
    },
    {
      "id": 197,
      "name": "John Deere Trucks",
      "description": "Tractor and dump truck toy.",
      "categoryId": "toys",
      "cost": 10,
      "price": 10,
      "ageRange": "6-8",
      "minAge": 6,
      "maxAge": 8,
      "ageGroup": "5to12",
      "image": "197John Deere Trucks.jpg"
    },
    {
      "id": 198,
      "name": "Magnetic Racer",
      "description": "Magnetic force power.",
      "categoryId": "toys",
      "cost": 7,
      "price": 7,
      "ageRange": "3-7",
      "minAge": 3,
      "maxAge": 7,
      "ageGroup": "5to12",
      "image": "198Magnetic Racer.png"
    },
    {
      "id": 199,
      "name": "Monster Trucks",
      "description": "Set of 4",
      "categoryId": "toys",
      "cost": 15,
      "price": 15,
      "ageRange": "2-5",
      "minAge": 2,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "199Monster Trucks.jpg"
    },
    {
      "id": 200,
      "name": "Neighbor's Garage",
      "description": "Garage play set. 2 cars included.",
      "categoryId": "toys",
      "cost": 16,
      "price": 16,
      "ageRange": "2-5",
      "minAge": 2,
      "maxAge": 5,
      "ageGroup": "under5",
      "image": "200AmazingMachines Big Bulldozers .jpg"
    }
  ],
};
