// src/data.js

// CATEGORY DEFINITIONS
// colorClass values match CSS classes in App.css
export const CATEGORIES = [
  { id: "browse-all",     name: "Browse all",     colorClass: "purple"   },
  { id: "toys",           name: "Toys",           colorClass: "pink"     },
  { id: "books",          name: "Books",          colorClass: "blue"     },
  { id: "sports",         name: "Sports",         colorClass: "green"    },
  { id: "games",          name: "Games",          colorClass: "yellow"   },
  { id: "gift-cards",     name: "Gift Cards",     colorClass: "peach"    },
  { id: "electronics",    name: "Electronics",    colorClass: "cyan"     },
  { id: "jewelry",        name: "Jewelry",        colorClass: "lavender" },
  { id: "arts-and-crafts",name: "Arts & Crafts",  colorClass: "coral"    },
  { id: "misc",           name: "Misc.",          colorClass: "mint"     },
  { id: "sweet-treats",   name: "Sweet Treats",   colorClass: "peach"    },
];


// PRODUCT DEFINITIONS
// Each key must match a category id (except "browse-all", which is special)
export const PRODUCTS = {
  "arts-and-crafts": [
  {
    "id": 400,
    "name": "Acrylic Art Paint Set",
    "description": "Painting Set",
    "categoryId": "arts-and-crafts",
    "cost": 27,
    "price": 27,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "400-acrylic-art-paint-set.jpg"
  },
  {
    "id": 401,
    "name": "Baby Sensory Crinkle Paper",
    "description": "Crinkle paper",
    "categoryId": "arts-and-crafts",
    "cost": 8,
    "price": 7,
    "ageRange": "1-2",
    "minAge": 1,
    "maxAge": 2,
    "ageGroup": "under5",
    "image": "401-baby-sensory-crinkle-paper.jpg"
  },
  {
    "id": 402,
    "name": "Bunch O Balloons",
    "description": "Water Balloons",
    "categoryId": "arts-and-crafts",
    "cost": 17,
    "price": 17,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "402-bunch-o-balloons.jpg"
  },
  {
    "id": 403,
    "name": "Classic Color Markers",
    "description": "Crayola Markers",
    "categoryId": "arts-and-crafts",
    "cost": 5,
    "price": 5,
    "ageRange": "3-10",
    "minAge": 3,
    "maxAge": 10,
    "ageGroup": "5to12",
    "image": "403-classic-color-markers.webp"
  },
  {
    "id": 404,
    "name": "Colored Pencils",
    "description": "48 Colored Pencils",
    "categoryId": "arts-and-crafts",
    "cost": 28,
    "price": 28,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "404-colored-pencils.png"
  },
  {
    "id": 405,
    "name": "Drawing Kit",
    "description": "103 Portable Zipper Case",
    "categoryId": "arts-and-crafts",
    "cost": 28,
    "price": 25,
    "ageRange": "11-18",
    "minAge": 11,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "405-drawing-kit.jpg"
  },
  {
    "id": 406,
    "name": "Drawing Pad",
    "description": "Sketching Pad",
    "categoryId": "arts-and-crafts",
    "cost": 8,
    "price": 20,
    "ageRange": "11-18",
    "minAge": 11,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "406-drawing-pad.jpg"
  },
  {
    "id": 407,
    "name": "Fingerprint Activities Animals Spiral-bound",
    "description": "Finger Painting",
    "categoryId": "arts-and-crafts",
    "cost": 15,
    "price": 15,
    "ageRange": "5-9",
    "minAge": 5,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "407-fingerprint-activities-animals-spiral-bound.jpg"
  },
  {
    "id": 408,
    "name": "Friendship Bracelet Thread",
    "description": "50+ colorful bracelet making",
    "categoryId": "arts-and-crafts",
    "cost": 10,
    "price": 6,
    "ageRange": "9-18",
    "minAge": 9,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "408-friendship-bracelet-thread.jpg"
  },
  {
    "id": 409,
    "name": "Hey Clay",
    "description": "Non sticky, toxic 5 cans Clay",
    "categoryId": "arts-and-crafts",
    "cost": 6,
    "price": 6,
    "ageRange": "4-15",
    "minAge": 4,
    "maxAge": 15,
    "ageGroup": "5to12",
    "image": "409-hey-clay.png"
  },
  {
    "id": 410,
    "name": "How to Write And Draw Your Own Comics",
    "description": "Intro to Comic book",
    "categoryId": "arts-and-crafts",
    "cost": 12,
    "price": 13,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "410-how-to-write-and-draw-your-own-comics.webp"
  },
  {
    "id": 411,
    "name": "Kinetic Sand",
    "description": "Sand never dries out",
    "categoryId": "arts-and-crafts",
    "cost": 21,
    "price": 21,
    "ageRange": "9-18",
    "minAge": 9,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "411-kinetic-sand.png"
  },
  {
    "id": 412,
    "name": "Liquid Motion Bubbler",
    "description": "Sensory fidget",
    "categoryId": "arts-and-crafts",
    "cost": 9,
    "price": 8,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "412-liquid-motion-bubbler.jpg"
  },
  {
    "id": 413,
    "name": "Modeling Clay",
    "description": "8 Colors of Clay",
    "categoryId": "arts-and-crafts",
    "cost": 8,
    "price": 9,
    "ageRange": "4-10",
    "minAge": 4,
    "maxAge": 10,
    "ageGroup": "5to12",
    "image": "413-modeling-clay.jpg"
  },
  {
    "id": 414,
    "name": "Pin Art",
    "description": "Fidget Impression Board",
    "categoryId": "arts-and-crafts",
    "cost": 13,
    "price": 9,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "414-pin-art.jpg"
  },
  {
    "id": 415,
    "name": "Shape Markers",
    "description": "Magnetic Foam Puzzles",
    "categoryId": "arts-and-crafts",
    "cost": 16,
    "price": 13,
    "ageRange": "6-11",
    "minAge": 6,
    "maxAge": 11,
    "ageGroup": "5to12",
    "image": "415-shape-markers.jpg"
  },
  {
    "id": 416,
    "name": "Sharpies Color Burst",
    "description": "Fine Point 12 Markers",
    "categoryId": "arts-and-crafts",
    "cost": 18,
    "price": 16,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "416-sharpies-color-burst.jpg"
  },
  {
    "id": 417,
    "name": "Sketch Pad",
    "description": "100 Sheets Paper",
    "categoryId": "arts-and-crafts",
    "cost": 18,
    "price": 8,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "417-sketch-pad.jpg"
  },
  {
    "id": 418,
    "name": "Travel Easel",
    "description": "37-Piece Art&Easel",
    "categoryId": "arts-and-crafts",
    "cost": 26,
    "price": 26,
    "ageRange": "4-7",
    "minAge": 4,
    "maxAge": 7,
    "ageGroup": "5to12",
    "image": "418-travel-easel.png"
  }
],

  "books": [
  {
    "id": 200,
    "name": "Amazing Machines: Big Bulldozers",
    "description": "Huge machines, digging fun",
    "categoryId": "books",
    "cost": 8,
    "price": 8,
    "ageRange": "4-6",
    "minAge": 4,
    "maxAge": 6,
    "ageGroup": "5to12",
    "image": "200-amazing-machines-big-bulldozers.jpg"
  },
  {
    "id": 201,
    "name": "Amazing Machines: Colossal Cranes",
    "description": "Tall machines, heavy lifting",
    "categoryId": "books",
    "cost": 9,
    "price": 9,
    "ageRange": "4-6",
    "minAge": 4,
    "maxAge": 6,
    "ageGroup": "5to12",
    "image": "201-amazing-machines-colossal-cranes.jpg"
  },
  {
    "id": 202,
    "name": "American Born Chinese",
    "description": "Jin Wang moves into a neighborhood to discover he is the only Chinese-American student at his new school.",
    "categoryId": "books",
    "cost": 10,
    "price": 10,
    "ageRange": "4-6",
    "minAge": 4,
    "maxAge": 6,
    "ageGroup": "5to12",
    "image": "202-american-born-chinese.jpg"
  },
  {
    "id": 203,
    "name": "Baby Boy, What Will You Be?",
    "description": "A book on possible life achievements for a child",
    "categoryId": "books",
    "cost": 12,
    "price": 12,
    "ageRange": "3-7",
    "minAge": 3,
    "maxAge": 7,
    "ageGroup": "5to12",
    "image": "203-baby-boy-what-will-you-be.jpeg"
  },
  {
    "id": 204,
    "name": "Baby Sign Language",
    "description": "Everyday baby sign language book",
    "categoryId": "books",
    "cost": 7,
    "price": 7,
    "ageRange": "1-2",
    "minAge": 1,
    "maxAge": 2,
    "ageGroup": "under5",
    "image": "204-baby-sign-language.jpg"
  },
  {
    "id": 205,
    "name": "Bad Guys Alien vs Bad Guys",
    "description": "Imaginary world of dinosaur playing, splashing, and singing. Coloring book.",
    "categoryId": "books",
    "cost": 8,
    "price": 8,
    "ageRange": "6-10",
    "minAge": 6,
    "maxAge": 10,
    "ageGroup": "5to12",
    "image": "205-bad-guys-alien-vs-bad-guys.jpg"
  },
  {
    "id": 206,
    "name": "Black Is a Rainbow Color",
    "description": "Celebration, love, powerful voices",
    "categoryId": "books",
    "cost": 9,
    "price": 9,
    "ageRange": "4-8",
    "minAge": 4,
    "maxAge": 8,
    "ageGroup": "5to12",
    "image": "206-black-is-a-rainbow-color.jpg"
  },
  {
    "id": 207,
    "name": "Black Joy",
    "description": "Celebrating",
    "categoryId": "books",
    "cost": 9,
    "price": 9,
    "ageRange": "4-8",
    "minAge": 4,
    "maxAge": 8,
    "ageGroup": "5to12",
    "image": "207-black-joy.jpg"
  },
  {
    "id": 208,
    "name": "Black Panther: Nation Under Our Feet",
    "description": "Superhero, King with Brave Battles",
    "categoryId": "books",
    "cost": 9,
    "price": 9,
    "ageRange": "6-10",
    "minAge": 6,
    "maxAge": 10,
    "ageGroup": "5to12",
    "image": "208-black-panther-nation-under-our-feet.jpg"
  },
  {
    "id": 209,
    "name": "Bletchley Riddle",
    "description": "Mystery solving",
    "categoryId": "books",
    "cost": 10,
    "price": 10,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "209-bletchley-riddle.jpg"
  },
  {
    "id": 210,
    "name": "Cat's Cradle",
    "description": "Science Fiction",
    "categoryId": "books",
    "cost": null,
    "price": null,
    "ageRange": "8-12",
    "minAge": 8,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "210-cat-s-cradle-book.jpg"
  },
  {
    "id": 211,
    "name": "Cookie of Doom",
    "description": "Fortune Cookie Story",
    "categoryId": "books",
    "cost": 8,
    "price": 8,
    "ageRange": "8-12",
    "minAge": 8,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "211-cookie-of-doom.jpg"
  },
  {
    "id": 212,
    "name": "Dinosaur Day",
    "description": "Rhyming Book to learn Dinosaurs",
    "categoryId": "books",
    "cost": 5,
    "price": 5,
    "ageRange": "4-8",
    "minAge": 4,
    "maxAge": 8,
    "ageGroup": "5to12",
    "image": "212-dinosaur-day.png"
  },
  {
    "id": 213,
    "name": "Full, Full, Full of Love",
    "description": "Joys of family and food.",
    "categoryId": "books",
    "cost": 6,
    "price": 6,
    "ageRange": "1-5",
    "minAge": 1,
    "maxAge": 5,
    "ageGroup": "under5",
    "image": "213-full-full-full-of-love.jpg"
  },
  {
    "id": 214,
    "name": "Girls Like Me",
    "description": "Girls like me",
    "categoryId": "books",
    "cost": 12,
    "price": 12,
    "ageRange": "3-9",
    "minAge": 3,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "214-girls-like-me.jpg"
  },
  {
    "id": 215,
    "name": "Goodnight Moon",
    "description": "Classic bedtime story.",
    "categoryId": "books",
    "cost": 6,
    "price": 6,
    "ageRange": "1-4",
    "minAge": 1,
    "maxAge": 4,
    "ageGroup": "under5",
    "image": "215-goodnight-moon.jpg"
  },
  {
    "id": 216,
    "name": "Hair Love",
    "description": "Love between fathers and daughters through hair care.",
    "categoryId": "books",
    "cost": 10,
    "price": 10,
    "ageRange": "1-4",
    "minAge": 1,
    "maxAge": 4,
    "ageGroup": "under5",
    "image": "216-hair-love.jpg"
  },
  {
    "id": 217,
    "name": "I Am Empowering African American for Boys",
    "description": "What it means to be confident, brave, and kind.",
    "categoryId": "books",
    "cost": 10,
    "price": 10,
    "ageRange": "2-6",
    "minAge": 2,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "217-i-am-empowering-african-american-for-boys.jpg"
  },
  {
    "id": 218,
    "name": "I Am Empowering Black and Brown Girls Natural Girly Hair",
    "description": "Building confidence, self-esteem, imagination, and spirit. Coloring book.",
    "categoryId": "books",
    "cost": 10,
    "price": 10,
    "ageRange": "3-6",
    "minAge": 3,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "218-i-am-empowering-black-and-brown-girls-natural-girly-hair.jpg"
  },
  {
    "id": 219,
    "name": "I Am Every Good Thing",
    "description": "Upbeat, empowering. Recognizing who we are.",
    "categoryId": "books",
    "cost": 13,
    "price": 13,
    "ageRange": "3-9",
    "minAge": 3,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "219-i-am-every-good-thing.jpg"
  },
  {
    "id": 220,
    "name": "I Know Why the Caged Bird Sings",
    "description": "Challenging struggles the author went through in early years of life.",
    "categoryId": "books",
    "cost": 8,
    "price": 8,
    "ageRange": "15-18",
    "minAge": 15,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "220-i-know-why-the-caged-bird-sings.webp"
  },
  {
    "id": 221,
    "name": "Interesting Facts for Curious Minds",
    "description": "Book with interesting facts.",
    "categoryId": "books",
    "cost": 13,
    "price": 13,
    "ageRange": "10-15",
    "minAge": 10,
    "maxAge": 15,
    "ageGroup": "12plus",
    "image": "221-interesting-facts-for-curious-minds.jpg"
  },
  {
    "id": 222,
    "name": "I Promise",
    "description": "LeBron James motivates children everywhere to always strive for greatness.",
    "categoryId": "books",
    "cost": 12,
    "price": 12,
    "ageRange": "4-8",
    "minAge": 4,
    "maxAge": 8,
    "ageGroup": "5to12",
    "image": "222-i-promise.jpg"
  },
  {
    "id": 223,
    "name": "Jabari Jumps",
    "description": "Overcoming fears.",
    "categoryId": "books",
    "cost": 7,
    "price": 7,
    "ageRange": "4-9",
    "minAge": 4,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "223-jabari-jumps.jpeg"
  },
  {
    "id": 224,
    "name": "Life Skills for Teens",
    "description": "Teens",
    "categoryId": "books",
    "cost": 9,
    "price": 9,
    "ageRange": "13-17",
    "minAge": 13,
    "maxAge": 17,
    "ageGroup": "12plus",
    "image": "224-life-skills-for-teens.jpg"
  },
  {
    "id": 225,
    "name": "Mommy, What Do You See When You Look At Me",
    "description": "Daughter challenges mom to answer questions.",
    "categoryId": "books",
    "cost": 10,
    "price": 10,
    "ageRange": "2-9",
    "minAge": 2,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "225-mommy-what-do-you-see-when-you-look-at-me.jpg"
  },
  {
    "id": 226,
    "name": "Parade of Elephants",
    "description": "Introduces basic concepts.",
    "categoryId": "books",
    "cost": 8,
    "price": 8,
    "ageRange": "1-4",
    "minAge": 1,
    "maxAge": 4,
    "ageGroup": "under5",
    "image": "226-parade-of-elephants.jpg"
  },
  {
    "id": 227,
    "name": "Sharks",
    "description": "Shark facts.",
    "categoryId": "books",
    "cost": 5,
    "price": 5,
    "ageRange": "4-8",
    "minAge": 4,
    "maxAge": 8,
    "ageGroup": "5to12",
    "image": "227-sharks.jpg"
  },
  {
    "id": 228,
    "name": "Snowy Day",
    "description": "Exploring a neighborhood after the first snow.",
    "categoryId": "books",
    "cost": 4,
    "price": 4,
    "ageRange": "1-4",
    "minAge": 1,
    "maxAge": 4,
    "ageGroup": "under5",
    "image": "228-snowy-day.jpg"
  },
  {
    "id": 229,
    "name": "Super Easy Teen Baking Cookbook",
    "description": "60 Simple Recipe",
    "categoryId": "books",
    "cost": 10,
    "price": 10,
    "ageRange": "13-16",
    "minAge": 13,
    "maxAge": 16,
    "ageGroup": "12plus",
    "image": "229-super-easy-teen-baking-cookbook.jpg"
  },
  {
    "id": 230,
    "name": "Unicorn Party",
    "description": "Six playful unicorns gather for a magical party. Coloring book.",
    "categoryId": "books",
    "cost": 8,
    "price": 8,
    "ageRange": "6-11",
    "minAge": 6,
    "maxAge": 11,
    "ageGroup": "5to12",
    "image": "230-unicorn-party.png"
  },
  {
    "id": 231,
    "name": "Where Does Pizza Come From?",
    "description": "Coloring",
    "categoryId": "books",
    "cost": 8,
    "price": 8,
    "ageRange": "4-9",
    "minAge": 4,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "231-where-does-pizza-come-from.jpg"
  }
],

  "electronics": [
  {
    "id": 900,
    "name": "Alarm Clock & Sound Machine",
    "description": "Sleep & Relax",
    "categoryId": "electronics",
    "cost": 20,
    "price": 20,
    "ageRange": "7-18",
    "minAge": 7,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "900-alarm-clock-and-sound-machine.jpg"
  },
  {
    "id": 901,
    "name": "Headphones - Wireless",
    "description": "Wireless Microphone",
    "categoryId": "electronics",
    "cost": 25,
    "price": 20,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "901-headphones-wireless.jpg"
  },
  {
    "id": 902,
    "name": "Lava Lamp",
    "description": "Swirling Colorful Glow Décor",
    "categoryId": "electronics",
    "cost": 32,
    "price": 30,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "902-lava-lamp.png"
  }
],

  "games": [
  {
    "id": 300,
    "name": "Bananagrams",
    "description": "Fast Paced Word Game",
    "categoryId": "games",
    "cost": 16,
    "price": 16,
    "ageRange": "7-18",
    "minAge": 7,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "300-bananagrams.jpg"
  },
  {
    "id": 301,
    "name": "CandyLand",
    "description": "Classic Board Game",
    "categoryId": "games",
    "cost": 13,
    "price": 13,
    "ageRange": "3-6",
    "minAge": 3,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "301-candyland.jpg"
  },
  {
    "id": 302,
    "name": "Checkers",
    "description": "Classic Board Game",
    "categoryId": "games",
    "cost": 10,
    "price": 10,
    "ageRange": "6-9",
    "minAge": 6,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "302-checkers.jpg"
  },
  {
    "id": 303,
    "name": "Chess, Checkers, Tic Tac Toe",
    "description": "Classic Board Game",
    "categoryId": "games",
    "cost": 20,
    "price": 20,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "303-chess-checkers-tic-tac-toe.jpg"
  },
  {
    "id": 304,
    "name": "Chutes and Ladders",
    "description": "Classic Board Game",
    "categoryId": "games",
    "cost": 9,
    "price": 9,
    "ageRange": "3-6",
    "minAge": 3,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "304-chutes-and-ladders.jpg"
  },
  {
    "id": 305,
    "name": "Connect 4 Board",
    "description": "Classic Board Game",
    "categoryId": "games",
    "cost": 9,
    "price": 9,
    "ageRange": "3-6",
    "minAge": 3,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "305-connect-4-board.jpg"
  },
  {
    "id": 306,
    "name": "Deck of Playing Cards",
    "description": "Classic Playing Cards",
    "categoryId": "games",
    "cost": 5,
    "price": 5,
    "ageRange": "6-18",
    "minAge": 6,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "306-deck-of-playing-cards.webp"
  },
  {
    "id": 307,
    "name": "Dungeon & Dragons Dice Set",
    "description": "Dice Set",
    "categoryId": "games",
    "cost": 7,
    "price": 7,
    "ageRange": "16-18",
    "minAge": 16,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "307-dungeon-and-dragons-dice-set.jpg"
  },
  {
    "id": 308,
    "name": "Dungeon & Dragons Mad Libs",
    "description": "Mad Libs",
    "categoryId": "games",
    "cost": 5,
    "price": 10,
    "ageRange": "16-18",
    "minAge": 16,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "308-dungeon-and-dragons-mad-libs.jpg"
  },
  {
    "id": 309,
    "name": "Dungeon & Dragons Mini Dice",
    "description": "7 Piece Metal Dice Set",
    "categoryId": "games",
    "cost": 15,
    "price": 15,
    "ageRange": "16-18",
    "minAge": 16,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "309-dungeon-and-dragons-mini-dice.jpg"
  },
  {
    "id": 310,
    "name": "Fabric Dart Board",
    "description": "Round hook-and-loop balls are the darts.",
    "categoryId": "games",
    "cost": 18,
    "price": 18,
    "ageRange": "4-12",
    "minAge": 4,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "310-fabric-dart-board.png"
  },
  {
    "id": 311,
    "name": "Jenga",
    "description": "Classic game of skill and strategy",
    "categoryId": "games",
    "cost": 11,
    "price": 11,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "311-jenga.jpg"
  },
  {
    "id": 312,
    "name": "Math Dice Jr.",
    "description": "Math Game",
    "categoryId": "games",
    "cost": 14,
    "price": 14,
    "ageRange": "6-12",
    "minAge": 6,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "312-math-dice-jr.jpg"
  },
  {
    "id": 313,
    "name": "Rat-a-tat Cat",
    "description": "Strategic Card Game",
    "categoryId": "games",
    "cost": 9,
    "price": 11,
    "ageRange": "6-13",
    "minAge": 6,
    "maxAge": 13,
    "ageGroup": "5to12",
    "image": "313-rat-a-tat-cat.jpg"
  },
  {
    "id": 314,
    "name": "Scrabble",
    "description": "Classic Board Game",
    "categoryId": "games",
    "cost": 22,
    "price": 10,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "314-scrabble.jpg"
  },
  {
    "id": 315,
    "name": "Seek-a-Boo",
    "description": "Memory Game",
    "categoryId": "games",
    "cost": 22,
    "price": 10,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "315-seek-a-boo.jfif"
  },
  {
    "id": 316,
    "name": "Sensory Bin - Outer Space",
    "description": "Explore and Learn Hands On",
    "categoryId": "games",
    "cost": 20,
    "price": 20,
    "ageRange": "4-13",
    "minAge": 4,
    "maxAge": 13,
    "ageGroup": "5to12",
    "image": "316-sensory-bin-outer-space.jpg"
  },
  {
    "id": 317,
    "name": "Slapzi",
    "description": "Fast Paced Picture Game",
    "categoryId": "games",
    "cost": 22,
    "price": 22,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "317-slapzi.jpg"
  },
  {
    "id": 318,
    "name": "Sleeping Queens",
    "description": "Strategic/Thinking Card Game",
    "categoryId": "games",
    "cost": 14,
    "price": 14,
    "ageRange": "9-18",
    "minAge": 9,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "318-sleeping-queens.png"
  },
  {
    "id": 319,
    "name": "Sorry",
    "description": "Classic Board Game",
    "categoryId": "games",
    "cost": 10,
    "price": 10,
    "ageRange": "6-15",
    "minAge": 6,
    "maxAge": 15,
    "ageGroup": "5to12",
    "image": "319-sorry.jpg"
  },
  {
    "id": 320,
    "name": "Splash Cards",
    "description": "Learning & Development",
    "categoryId": "games",
    "cost": 10,
    "price": 10,
    "ageRange": "3-7",
    "minAge": 3,
    "maxAge": 7,
    "ageGroup": "5to12",
    "image": "320-splash-cards.jpg"
  },
  {
    "id": 321,
    "name": "Stress(No) Chess",
    "description": "Learn Chess w/o Stress",
    "categoryId": "games",
    "cost": 13,
    "price": 13,
    "ageRange": "5-18",
    "minAge": 5,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "321-stress-no-chess.png"
  },
  {
    "id": 322,
    "name": "Trouble Board",
    "description": "Classic Board Game",
    "categoryId": "games",
    "cost": 9,
    "price": 9,
    "ageRange": "5-18",
    "minAge": 5,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "322-trouble-board.jpg"
  },
  {
    "id": 323,
    "name": "Uno",
    "description": "Matching Colors & Numbers",
    "categoryId": "games",
    "cost": 5,
    "price": 7,
    "ageRange": "7-18",
    "minAge": 7,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "323-uno.jpg"
  },
  {
    "id": 324,
    "name": "Yahtzee",
    "description": "Classic Dice Game",
    "categoryId": "games",
    "cost": 9,
    "price": 9,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "324-yahtzee.jpg"
  }
],

  "gift-cards": [
  {
    "id": 800,
    "name": "Old Navy",
    "description": "Clothing",
    "categoryId": "gift-cards",
    "cost": 30,
    "price": 30,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "800-old-navy.jpg"
  },
  {
    "id": 801,
    "name": "PH Coffee",
    "description": "Café",
    "categoryId": "gift-cards",
    "cost": 15,
    "price": 15,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "801-ph-coffee.png"
  },
  {
    "id": 802,
    "name": "Subway",
    "description": "Sandwich Restaurant",
    "categoryId": "gift-cards",
    "cost": 15,
    "price": 15,
    "ageRange": "6-18",
    "minAge": 6,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "802-subway.png"
  },
  {
    "id": 803,
    "name": "Chipotle",
    "description": "American Mexican Restaurant",
    "categoryId": "gift-cards",
    "cost": 20,
    "price": 20,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "803-chipotle.jpg"
  },
  {
    "id": 804,
    "name": "TJ Maxx",
    "description": "Clothing",
    "categoryId": "gift-cards",
    "cost": 50,
    "price": 50,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "804-tj-maxx.jpg"
  },
  {
    "id": 805,
    "name": "Sky Zone",
    "description": "Trampoline Activities",
    "categoryId": "gift-cards",
    "cost": 25,
    "price": 25,
    "ageRange": "6-18",
    "minAge": 6,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "805-sky-zone.webp"
  },
  {
    "id": 806,
    "name": "Cici's",
    "description": "Pizza Restaurant",
    "categoryId": "gift-cards",
    "cost": 25,
    "price": 25,
    "ageRange": "6-18",
    "minAge": 6,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "806-cicis-pizza-gift-card.png"
  },
  {
    "id": 807,
    "name": "Ulta",
    "description": "Beauty Aesthetic Store",
    "categoryId": "gift-cards",
    "cost": 15,
    "price": 15,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "807-ulta.jpg"
  },
  {
    "id": 808,
    "name": "QuikTrip",
    "description": "Convenience Store",
    "categoryId": "gift-cards",
    "cost": 25,
    "price": 25,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "808-quiktrip.jpg"
  },
  {
    "id": 809,
    "name": "Little Caesar's",
    "description": "Pizza Restaurant",
    "categoryId": "gift-cards",
    "cost": 30,
    "price": 30,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "809-little-caesars-pizza-gift-card.webp"
  },
  {
    "id": 810,
    "name": "Fritz's",
    "description": "American Burger Restaurant",
    "categoryId": "gift-cards",
    "cost": 30,
    "price": 30,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "810-fritz-s-gift-card.webp"
  },
  {
    "id": 811,
    "name": "Yogurtini",
    "description": "Self Serve Restaurant",
    "categoryId": "gift-cards",
    "cost": 15,
    "price": 15,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "811-yogurtini.png"
  },
  {
    "id": 812,
    "name": "Dairy Queen",
    "description": "American Food and Ice Cream",
    "categoryId": "gift-cards",
    "cost": 20,
    "price": 20,
    "ageRange": "1-18",
    "minAge": 1,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "812-dairy-queen.jpg"
  },
  {
    "id": 813,
    "name": "Pizza Street",
    "description": "Pizza Restaurant",
    "categoryId": "gift-cards",
    "cost": 10,
    "price": 10,
    "ageRange": "3-9",
    "minAge": 3,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "813-pizza-street.jpg"
  },

  {
    "id": 815,
    "name": "Nut Allergy Gift Card",
    "description": "Nut Allergy",
    "categoryId": "gift-cards",
    "cost": 22,
    "price": 22,
    "ageRange": "3-18",
    "minAge": 3,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "815-nut-allergy-gift-card.jpg"
  }
],

  "jewelry": [
  {
    "id": 500,
    "name": "Beaded Bracelet",
    "description": "12pcs Beaded Friendship Bracelets",
    "categoryId": "jewelry",
    "cost": 7,
    "price": 7,
    "ageRange": "11-18",
    "minAge": 11,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "500-beaded-bracelet.jpg"
  },
  {
    "id": 501,
    "name": "Good Vibes Necklace",
    "description": "21\" silver chain.",
    "categoryId": "jewelry",
    "cost": 6,
    "price": 6,
    "ageRange": "12-18",
    "minAge": 12,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "501-good-vibes-necklace.jpg"
  },
  {
    "id": 502,
    "name": "Initial Necklace",
    "description": "18\" Hypoallergenic.",
    "categoryId": "jewelry",
    "cost": 9,
    "price": 9,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "502-initial-necklace.webp"
  },
  {
    "id": 503,
    "name": "Layered necklace",
    "description": "Layered Necklace",
    "categoryId": "jewelry",
    "cost": 16,
    "price": 16,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "503-layered-necklace.jpg"
  },
  {
    "id": 504,
    "name": "Leather Bracelet",
    "description": "Leather cuffed Adjustable",
    "categoryId": "jewelry",
    "cost": 10,
    "price": 10,
    "ageRange": "15-18",
    "minAge": 15,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "504-leather-bracelet.jpg"
  },
  {
    "id": 505,
    "name": "Leather Wrap Bracelets",
    "description": "Double Hearts Infinity",
    "categoryId": "jewelry",
    "cost": 5,
    "price": 5,
    "ageRange": "11-18",
    "minAge": 11,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "505-leather-wrap-bracelets.jpg"
  },
  {
    "id": 506,
    "name": "Multilayer Bracelet",
    "description": "Gender neutral beaded hemp cords",
    "categoryId": "jewelry",
    "cost": 6,
    "price": 6,
    "ageRange": "12-18",
    "minAge": 12,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "506-multilayer-bracelet.jpg"
  },
  {
    "id": 507,
    "name": "Tree of Life Bracelets",
    "description": "Leather Tree of life Bracelets",
    "categoryId": "jewelry",
    "cost": 10,
    "price": 10,
    "ageRange": "14-18",
    "minAge": 14,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "507-tree-of-life-bracelets.jpg"
  },
  {
    "id": 508,
    "name": "Twisted Rope Chain",
    "description": "Rope Chains - 16\"-30\"",
    "categoryId": "jewelry",
    "cost": 21,
    "price": 21,
    "ageRange": "15-18",
    "minAge": 15,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "508-twisted-rope-chain.jpg"
  }
],

  "misc": [
  {
    "id": 700,
    "name": "Break Open Geode",
    "description": "10 crystal filled geodes. Includes safety goggles.",
    "categoryId": "misc",
    "cost": 12,
    "price": 12,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "700-break-open-geode.jpg"
  },
  {
    "id": 701,
    "name": "Color Changing Cup",
    "description": "6-pack, Lids and Straws",
    "categoryId": "misc",
    "cost": 13,
    "price": 13,
    "ageRange": "5-8",
    "minAge": 5,
    "maxAge": 8,
    "ageGroup": "5to12",
    "image": "701-color-changing-cup.jpg"
  },
  {
    "id": 702,
    "name": "Croc Charms",
    "description": "25 Croc Charms",
    "categoryId": "misc",
    "cost": 6,
    "price": 6,
    "ageRange": "5-18",
    "minAge": 5,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "702-croc-charms.jpg"
  },
  {
    "id": 703,
    "name": "Crossbody Backback",
    "description": "Carry All the Essentials",
    "categoryId": "misc",
    "cost": 17,
    "price": 17,
    "ageRange": "12-18",
    "minAge": 12,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "703-crossbody-backback.jpg"
  },
  {
    "id": 704,
    "name": "Personalized Blanket",
    "description": "Personalized Blanket",
    "categoryId": "misc",
    "cost": 50,
    "price": 50,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "704-personalized-blanket.webp"
  },
  {
    "id": 705,
    "name": "Shark Hooded Baby Towel",
    "description": "100% cotton towel.",
    "categoryId": "misc",
    "cost": 17,
    "price": 17,
    "ageRange": "1-2",
    "minAge": 1,
    "maxAge": 2,
    "ageGroup": "under5",
    "image": "705-shark-hooded-baby-towel.png"
  },
  {
    "id": 706,
    "name": "Thermos Sports Jug",
    "description": "Half Gallon",
    "categoryId": "misc",
    "cost": 14,
    "price": 14,
    "ageRange": "10-18",
    "minAge": 10,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "706-thermos-sports-jug.jpg"
  },
  {
    "id": 707,
    "name": "Towels",
    "description": "Hooded Bath Blanket. Selection will vary.",
    "categoryId": "misc",
    "cost": 26,
    "price": 26,
    "ageRange": "1-2",
    "minAge": 1,
    "maxAge": 2,
    "ageGroup": "under5",
    "image": "707-towels.jpg"
  },
  {
    "id": 708,
    "name": "Water Bottle for kids",
    "description": "12 oz Stainless Steel",
    "categoryId": "misc",
    "cost": 10,
    "price": 10,
    "ageRange": "2-8",
    "minAge": 2,
    "maxAge": 8,
    "ageGroup": "5to12",
    "image": "708-water-bottle-for-kids.jpg"
  },
  {
    "id": 709,
    "name": "Water Cup - Large",
    "description": "40 oz insulated, handle",
    "categoryId": "misc",
    "cost": 15,
    "price": 15,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "709-water-cup-large.jpg"
  },
  {
    "id": 710,
    "name": "Water Cup - Medium",
    "description": "20 oz insulated, handle",
    "categoryId": "misc",
    "cost": 12,
    "price": 12,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "710-water-cup-medium.jpg"
  },
  {
    "id": 711,
    "name": "White Fuzzy Rug",
    "description": "4x6",
    "categoryId": "misc",
    "cost": 35,
    "price": 35,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "711-white-fuzzy-rug.jpg"
  },
  {
    "id": 712,
    "name": "It's my Birthday Pin",
    "description": "Fun pin to wear on your birthday. Selection varies.",
    "categoryId": "misc",
    "cost": 5,
    "price": 3,
    "ageRange": "3-18",
    "minAge": 3,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "712-its-my-birthday-pin.jpg"
  }
],

  "sports": [
  {
    "id": 600,
    "name": "Balls for Toddler",
    "description": "Foam play sports balls",
    "categoryId": "sports",
    "cost": 25,
    "price": 20,
    "ageRange": "1-2",
    "minAge": 1,
    "maxAge": 2,
    "ageGroup": "under5",
    "image": "600-balls-for-toddler.png"
  },
  {
    "id": 601,
    "name": "Baseball 3 in 1 Set for Kids 3-5 Adjustable Height",
    "description": "Tee Ball Stand, Hanging Tee, Ball Launcher and 6 Softballs",
    "categoryId": "sports",
    "cost": 15,
    "price": 24,
    "ageRange": "2-3",
    "minAge": 2,
    "maxAge": 3,
    "ageGroup": "under5",
    "image": "601-baseball-3-in-1-set-for-kids-3-5-adjustable-height.jpg"
  },
  {
    "id": 602,
    "name": "Basketball",
    "description": "Orange -Size 7 (29.5\")",
    "categoryId": "sports",
    "cost": 13,
    "price": 13,
    "ageRange": "13-18",
    "minAge": 13,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "602-basketball.jpg"
  },
  {
    "id": 603,
    "name": "Basketball Kids",
    "description": "Orange - Size 5 (27.5\")",
    "categoryId": "sports",
    "cost": 13,
    "price": 13,
    "ageRange": "10-12",
    "minAge": 10,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "603-basketball-kids.jpg"
  },
  {
    "id": 604,
    "name": "Basketball Youth",
    "description": "Orange - size 3 (23\")",
    "categoryId": "sports",
    "cost": 10,
    "price": 10,
    "ageRange": "4-9",
    "minAge": 4,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "604-basketball-youth.jpg"
  },
  {
    "id": 605,
    "name": "Double Jump Rope",
    "description": "16 feet",
    "categoryId": "sports",
    "cost": 16,
    "price": 16,
    "ageRange": "6-18",
    "minAge": 6,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "605-double-jump-rope.png"
  },
  {
    "id": 606,
    "name": "Fishing Rod and Reel Combo",
    "description": "34\" fishing rod & reel. Includes safety hook.",
    "categoryId": "sports",
    "cost": 25,
    "price": 25,
    "ageRange": "6-18",
    "minAge": 6,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "606-fishing-rod-and-reel-combo.jpg"
  },
  {
    "id": 607,
    "name": "Football",
    "description": "Football",
    "categoryId": "sports",
    "cost": 15,
    "price": 15,
    "ageRange": "8-12",
    "minAge": 8,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "607-football.jpg"
  },
  {
    "id": 608,
    "name": "Football - Chiefs",
    "description": "Chiefs! Junior 8.5\"",
    "categoryId": "sports",
    "cost": 15,
    "price": 15,
    "ageRange": "5-9",
    "minAge": 5,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "608-football-chiefs.jpg"
  },
  {
    "id": 609,
    "name": "Football Kicking Tee",
    "description": "Size 1\" standard football kick-off kicking tee",
    "categoryId": "sports",
    "cost": 5,
    "price": 5,
    "ageRange": "6-18",
    "minAge": 6,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "609-football-kicking-tee.jpg"
  },
  {
    "id": 610,
    "name": "Football Youth",
    "description": "Youth size",
    "categoryId": "sports",
    "cost": 12,
    "price": 14,
    "ageRange": "6-11",
    "minAge": 6,
    "maxAge": 11,
    "ageGroup": "5to12",
    "image": "610-football-youth.jpg"
  },
  {
    "id": 611,
    "name": "L.O.L. Surprise! Quad Adjustable Roller Skate",
    "description": "Easy beginner skates. Recommended for a shoe size of 10-13",
    "categoryId": "sports",
    "cost": 40,
    "price": 40,
    "ageRange": "4-6",
    "minAge": 4,
    "maxAge": 6,
    "ageGroup": "5to12",
    "image": "611-lol-surprise-quad-adjustable-roller-skate.png"
  },
  {
    "id": 612,
    "name": "Mini Basketball Hoop",
    "description": "Over the door mount",
    "categoryId": "sports",
    "cost": 35,
    "price": 35,
    "ageRange": "6-18",
    "minAge": 6,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "612-mini-basketball-hoop.jpg"
  },
  {
    "id": 613,
    "name": "Pro Vision 31 Skateboard",
    "description": "Fully assembled with grip-tape and skate hardware.",
    "categoryId": "sports",
    "cost": 40,
    "price": 40,
    "ageRange": "8-18",
    "minAge": 8,
    "maxAge": 18,
    "ageGroup": "12plus",
    "image": "613-pro-vision-31-skateboard.jpg"
  },
  {
    "id": 614,
    "name": "Punt, Pass And Shoot Ball Set",
    "description": "Baseball, basketball, soccer ball, and football set.",
    "categoryId": "sports",
    "cost": 14,
    "price": 14,
    "ageRange": "3-6",
    "minAge": 3,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "614-punt-pass-and-shoot-ball-set.webp"
  },
  {
    "id": 615,
    "name": "Push & Pop Bulldozer",
    "description": "Pop! Pop! Pop!",
    "categoryId": "sports",
    "cost": 25,
    "price": 25,
    "ageRange": "2-4",
    "minAge": 2,
    "maxAge": 4,
    "ageGroup": "under5",
    "image": "615-push-and-pop-bulldozer.jpg"
  },
  {
    "id": 616,
    "name": "Razor A Kick Scooter",
    "description": "Classic scooter,Lightweight,Folds easily",
    "categoryId": "sports",
    "cost": 30,
    "price": 30,
    "ageRange": "5-12",
    "minAge": 5,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "616-razor-a-kick-scooter.png"
  },
  {
    "id": 617,
    "name": "Single Jump Rope",
    "description": "8 ft Jump rope",
    "categoryId": "sports",
    "cost": 10,
    "price": 10,
    "ageRange": "5-18",
    "minAge": 5,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "617-single-jump-rope.png"
  },
  {
    "id": 618,
    "name": "Soccer Ball",
    "description": "Kickball",
    "categoryId": "sports",
    "cost": 19,
    "price": 15,
    "ageRange": "13-15",
    "minAge": 13,
    "maxAge": 15,
    "ageGroup": "12plus",
    "image": "618-soccer-ball.jpg"
  },
  {
    "id": 619,
    "name": "Soccer Ball - youth",
    "description": "Kickball",
    "categoryId": "sports",
    "cost": 15,
    "price": 15,
    "ageRange": "8-12",
    "minAge": 8,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "619-soccer-ball-youth.jpg"
  },
  {
    "id": 620,
    "name": "Sonic Fin Football",
    "description": "Aerodynamic toy",
    "categoryId": "sports",
    "cost": 15,
    "price": 15,
    "ageRange": "6-12",
    "minAge": 6,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "620-sonic-fin-football.jpg"
  },
  {
    "id": 621,
    "name": "Youth Inline Skate",
    "description": "Adjustable Fit, Gliding Action",
    "categoryId": "sports",
    "cost": 38,
    "price": 38,
    "ageRange": "7-10",
    "minAge": 7,
    "maxAge": 10,
    "ageGroup": "5to12",
    "image": "621-youth-inline-skate.png"
  }
],

  "sweet-treats": [
  {
    "id": 1000,
    "name": "HB",
    "description": "Happy Birthday!",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "1000-hb.jpg"
  },
  {
    "id": 1001,
    "name": "HB",
    "description": "Happy Birthday!",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "1001-hb.jpg"
  },
  {
    "id": 1002,
    "name": "HB",
    "description": "Happy Birthday!",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "1002-hb.jpg"
  },
  {
    "id": 1003,
    "name": "HB",
    "description": "Happy Birthday!",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "1003-hb.jpg"
  },
  {
    "id": 1004,
    "name": "HB",
    "description": "Happy Birthday!",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "1004-hb.jpg"
  },
  {
    "id": 1005,
    "name": "HB",
    "description": "Happy Birthday!",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "1005-hb.jpg"
  },

  {
    "id": 2000,
    "name": "CC Cookie Cake & Vanilla Frosting",
    "description": "Cake",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2000-cc-cookie-cake-and-vanilla-frosting.jpeg"
  },
  {
    "id": 2001,
    "name": "CC Cookie Cake & Chocolate Frosting",
    "description": "Cake",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2001-cc-cookie-cake-and-chocolate-frosting.jpeg"
  },
  {
    "id": 2002,
    "name": "Chocolate Cake Chocolate Frosting",
    "description": "Cake",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2002-chocolate-cake-chocolate-frosting.jpeg"
  },
  {
    "id": 2003,
    "name": "Chocolate Cake Vanilla Frosting",
    "description": "Cake",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2003-chocolate-cake-vanilla-frosting.jpeg"
  },
  {
    "id": 2004,
    "name": "Chocolate Chip Cookie",
    "description": "Cookie",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2004-chocolate-chip-cookie.jpeg"
  },
  {
    "id": 2005,
    "name": "Cookies Brownie",
    "description": "Brownie",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2005-cookies-browine.jpeg"
  },
  {
    "id": 2006,
    "name": "Cookies Chocolate Chip",
    "description": "Cookie",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2006-cookies-chocolate-chip.jpeg"
  },
  {
    "id": 2007,
    "name": "Cookies Sugar",
    "description": "Cookie",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2007-cookies-sugar.jpeg"
  },
  {
    "id": 2008,
    "name": "Dairy Free Cake Vanilla Frosting",
    "description": "Cake",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2008-dairy-free-cake-vanilla-frosting.jpeg"
  },
  {
    "id": 2009,
    "name": "Marble Cake Chocolate Frosting",
    "description": "Cake",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2009-marble-cake-chocolate-frosting.jpeg"
  },
  {
    "id": 2010,
    "name": "Marble Cake Vanilla Frosting",
    "description": "Cake",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2010-marble-cake-vanilla-frosting.jpeg"
  },
  {
    "id": 2011,
    "name": "White Cake Chocolate Frosting",
    "description": "Cake",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2011-white-cake-chocolate-frosting.jpeg"
  },
  {
    "id": 2012,
    "name": "White Cake Vanilla Frosting",
    "description": "Cake",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "ageGroup": null,
    "image": "2012-white-cake-vanilla-frosting.jpeg"
  },
  {
    "id": 2013,
    "name": "Cookies M&M",
    "description": "Cookie",
    "categoryId": "sweet-treats",
    "cost": 0,
    "price": 0,
    "ageRange": null,
    "minAge": null,
    "maxAge": null,
    "image": "2013-cookies-mandm.jpeg"
  },

  {
    "id": 3000,
    "name": "Paper Streamers",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3000-paper-streamers.png",
    "cost": 0,
    "price": 0
  },
  {
    "id": 3001,
    "name": "Candles",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3001-candles.png",
    "cost": 0,
    "price": 0
  },
  {
    "id": 3002,
    "name": "Scissors",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3002-scissors.png",
    "cost": 0,
    "price": 0
  },
  {
    "id": 3003,
    "name": "Tape",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3003-tape.png",
    "cost": 0,
    "price": 0
  },
  {
    "id": 3004,
    "name": "Gift Bag",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3004-gift-bag.png",
    "cost": 0,
    "price": 0
  },
  {
    "id": 3005,
    "name": "Gift Bag",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3005-gift-bag.png",
    "cost": 0,
    "price": 0
  },
  {
    "id": 3006,
    "name": "Candle Bag",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3006-candle-bag.png",
    "cost": 0,
    "price": 0
  },
  {
    "id": 3007,
    "name": "Gift Bag",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3007-gift-bag.png",
    "cost": 0,
    "price": 0
  },
  {
    "id": 3008,
    "name": "Candle Bag",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3008-candle-bag.png",
    "cost": 0,
    "price": 0
  },
  {
    "id": 3009,
    "name": "Candle Bag",
    "description": "Supplies",
    "categoryId": "sweet-treats",
    "image": "3009-candle-bag.png",
    "cost": 0,
    "price": 0
  }
],
 "toys": [
  {
    "id": 101,
    "name": "Alaphabet Express",
    "description": "28 Piece alphabet floor puzzle",
    "categoryId": "toys",
    "cost": 5,
    "price": 5,
    "ageRange": "3-6",
    "minAge": 3,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "101-alaphabet-express.jpg"
  },
  {
    "id": 102,
    "name": "Baby's First Blocks",
    "description": "10 Shapes for sorting",
    "categoryId": "toys",
    "cost": 10,
    "price": 10,
    "ageRange": "1-2",
    "minAge": 1,
    "maxAge": 2,
    "ageGroup": "under5",
    "image": "102-babys-first-blocks.jpg"
  },
  {
    "id": 103,
    "name": "Baby Multi-Sensory Blocks",
    "description": "ABC, Animals, Colors",
    "categoryId": "toys",
    "cost": 15,
    "price": 15,
    "ageRange": "1-5",
    "minAge": 1,
    "maxAge": 5,
    "ageGroup": "under5",
    "image": "103-baby-multi-sensory-blocks.jpg"
  },
  {
    "id": 104,
    "name": "Binoculars",
    "description": "Includes a neck strap",
    "categoryId": "toys",
    "cost": 12,
    "price": 12,
    "ageRange": "6-9",
    "minAge": 6,
    "maxAge": 9,
    "ageGroup": "5to12",
    "image": "104-binoculars.jpg"
  },
  {
    "id": 105,
    "name": "Blanket - Funny Pizza",
    "description": "Flannel",
    "categoryId": "toys",
    "cost": 30,
    "price": 30,
    "ageRange": "5-18",
    "minAge": 5,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "105-blanket-funny-pizza.jpg"
  },
  {
    "id": 106,
    "name": "Buddy the Cat Ride-on",
    "description": "Handle to give a helping hand.",
    "categoryId": "toys",
    "cost": 26,
    "price": 26,
    "ageRange": "1-3",
    "minAge": 1,
    "maxAge": 3,
    "ageGroup": "under5",
    "image": "106-buddy-the-cat-ride-on.jpg"
  },
  {
    "id": 107,
    "name": "Bug Viewer,Catcher, & Magnifier",
    "description": "Butterfly net, observation jar, insect collection box, tweezers, magnifying glass.",
    "categoryId": "toys",
    "cost": 18,
    "price": 18,
    "ageRange": "3-6",
    "minAge": 3,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "107-bug-viewer-catcher-and-magnifier.jpg"

  },
  {
    "id": 108,
    "name": "Burger and Fries",
    "description": "Stress reliever fidget.",
    "categoryId": "toys",
    "cost": 7,
    "price": 7,
    "ageRange": "2-18",
    "minAge": 2,
    "maxAge": 18,
    "ageGroup": "5to12",
    "image": "108-burger-and-fries.jpg"
  },
  {
    "id": 109,
    "name": "Calico Cat Warmie",
    "description": "Microwave or freezer for stress relief, reduce anxiety",
    "categoryId": "toys",
    "cost": 25,
    "price": 25,
    "ageRange": "3-13",
    "minAge": 3,
    "maxAge": 13,
    "ageGroup": "5to12",
    "image": "109-calico-cat-warmie.png"
  },
  {
    "id": 110,
    "name": "Carpenter Dress Up Set",
    "description": "Dress construction worker.",
    "categoryId": "toys",
    "cost": 22,
    "price": 22,
    "ageRange": "3-6",
    "minAge": 3,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "110-carpenter-dress-up-set.webp"
  },
  {
    "id": 111,
    "name": "Caterpillar Xylophone",
    "description": "Music fun! Wooden",
    "categoryId": "toys",
    "cost": 11,
    "price": 11,
    "ageRange": "3-6",
    "minAge": 3,
    "maxAge": 6,
    "ageGroup": "under5",
    "image": "111-caterpillar-xylophone.jpg"
  },
  {
    "id": 112,
    "name": "Clean Up Set",
    "description": "Cleaning set.",
    "categoryId": "toys",
    "cost": 18,
    "price": 18,
    "ageRange": "3-5",
    "minAge": 3,
    "maxAge": 5,
    "ageGroup": "under5",
    "image": "112-clean-up-set.jpg"
  },
  {
    "id": 113,
    "name": "Corn Popper",
    "description": "Classic push toy.",
    "categoryId": "toys",
    "cost": 14,
    "price": 14,
    "ageRange": "1-2",
    "minAge": 1,
    "maxAge": 2,
    "ageGroup": "under5",
    "image": "113-corn-popper.jpg"
  },
  {
    "id": 114,
    "name": "Crinkle Toy",
    "description": "Perfect for playing, car seats, and strollers.",
    "categoryId": "toys",
    "cost": 15,
    "price": 15,
    "ageRange": "1-2",
    "minAge": 1,
    "maxAge": 2,
    "ageGroup": "under5",
    "image": "114-crinkle-toy.jpg"
  },
  {
    "id": 115,
    "name": "Dig It Up - Volcano",
    "description": "Volcano surprise! Dig out fascinating artifacts!",
    "categoryId": "toys",
    "cost": 5,
    "price": 5,
    "ageRange": "8-12",
    "minAge": 8,
    "maxAge": 12,
    "ageGroup": "5to12",
    "image": "115-dig-it-up-volcano.jpeg"
  },
  {
    "id": 116,
    "name": "Dimple Digit",
    "description": "Touch, push, pop. 1 to 10 in English and Spanish.",
    "categoryId": "toys",
    "cost": 16,
    "price": 16,
    "ageRange": "3-5",
    "minAge": 3,
    "maxAge": 5,
    "ageGroup": "under5",
    "image": "116-dimple-digit.jpg"
  },
    {
  "id": 117,
  "name": "Dishwashing Fun Set",
  "description": "Play washing dishes. CHOKING HAZARD: Small parts. Not for children under 3 years.",
  "categoryId": "toys",
  "cost": 15,
  "price": 15,
  "ageRange": "4-6",
  "minAge": 4,
  "maxAge": 6,
  "ageGroup": "5to12",
  "image": "117-dishwashing-fun-set.jpg"
},
{
  "id": 118,
  "name": "Easy Grasp Ball",
  "description": "Classic toy!",
  "categoryId": "toys",
  "cost": 5,
  "price": 5,
  "ageRange": "1-3",
  "minAge": 1,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "118-easy-grasp-ball.jpg"
},
{
  "id": 119,
  "name": "Floor Piano Playmat",
  "description": "Step on Musical Floor Mat",
  "categoryId": "toys",
  "cost": 26,
  "price": 26,
  "ageRange": "2-6",
  "minAge": 2,
  "maxAge": 6,
  "ageGroup": "under5",
  "image": "119-floor-piano-playmat.jpg"
},
{
  "id": 120,
  "name": "Golden Dog Warmies",
  "description": "13\". Microwave or freezer for stress relief, reduce anxiety. Lavender.",
  "categoryId": "toys",
  "cost": 21,
  "price": 21,
  "ageRange": "3-18",
  "minAge": 3,
  "maxAge": 18,
  "ageGroup": "5to12",
  "image": "120-golden-dog-warmies.png"
},
{
  "id": 121,
  "name": "Johnny Jungle Plane",
  "description": "Friction-powered",
  "categoryId": "toys",
  "cost": 33,
  "price": 33,
  "ageRange": "1-4",
  "minAge": 1,
  "maxAge": 4,
  "ageGroup": "under5",
  "image": "121-johnny-jungle-plane.jpeg"
},
{
  "id": 122,
  "name": "Jungle Maracas Egg Shakers",
  "description": "3-piece set.",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "1-3",
  "minAge": 1,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "122-jungle-maracas-egg-shakers.jpg"
},
{
  "id": 123,
  "name": "Karaoke Microphone",
  "description": "Bluetooth karaoke microphone with speaker.",
  "categoryId": "toys",
  "cost": 20,
  "price": 20,
  "ageRange": "8-12",
  "minAge": 8,
  "maxAge": 12,
  "ageGroup": "5to12",
  "image": "123-karaoke-microphone.jpg"
},
{
  "id": 124,
  "name": "Kitchen Set",
  "description": "Wooden cooking set.",
  "categoryId": "toys",
  "cost": 25,
  "price": 25,
  "ageRange": "2-3",
  "minAge": 2,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "124-kitchen-set.jpg"
},
{
  "id": 125,
  "name": "Kittens",
  "description": "4 miniture kitties",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "6-10",
  "minAge": 6,
  "maxAge": 10,
  "ageGroup": "5to12",
  "image": "125-kittens.jpg"
},
{
  "id": 126,
  "name": "LiquiFly FizzRocket",
  "description": "Launch with baking soda and vinegar.",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "12-18",
  "minAge": 12,
  "maxAge": 18,
  "ageGroup": "12plus",
  "image": "126-liquifly-fizzrocket.png"
},
{
  "id": 127,
  "name": "Magnetic Tiles Toys",
  "description": "40 magnetic building tiles",
  "categoryId": "toys",
  "cost": 36,
  "price": 36,
  "ageRange": "4-9",
  "minAge": 4,
  "maxAge": 9,
  "ageGroup": "5to12",
  "image": "127-magnetic-tiles-toys.png"
},
{
  "id": 128,
  "name": "Makeup & Bag",
  "description": "Cosmetics Set",
  "categoryId": "toys",
  "cost": 20,
  "price": 20,
  "ageRange": "14-16",
  "minAge": 14,
  "maxAge": 16,
  "ageGroup": "12plus",
  "image": "128-makeup-and-bag.jpg"
},
{
  "id": 129,
  "name": "Make-up Brushes",
  "description": "Makeup Set",
  "categoryId": "toys",
  "cost": 4,
  "price": 4,
  "ageRange": "13-18",
  "minAge": 13,
  "maxAge": 18,
  "ageGroup": "12plus",
  "image": "129-make-up-brushes.jpg"
},
{
  "id": 130,
  "name": "Makeup Essentials",
  "description": "Makeup Set",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "14-18",
  "minAge": 14,
  "maxAge": 18,
  "ageGroup": "12plus",
  "image": "130-makeup-essentials.jpg"
},
{
  "id": 131,
  "name": "Marble Run",
  "description": "Create your own design. NOT SUITABLE FOR CHILDREN 3 AND UNDER.",
  "categoryId": "toys",
  "cost": 27,
  "price": 27,
  "ageRange": "6-12",
  "minAge": 6,
  "maxAge": 12,
  "ageGroup": "5to12",
  "image": "131-marble-run.jpg"
},
{
  "id": 132,
  "name": "Marble Tracks Builder Set",
  "description": "Create your own design. NOT SUITABLE FOR CHILDREN 3 AND UNDER.",
  "categoryId": "toys",
  "cost": 23,
  "price": 23,
  "ageRange": "8-10",
  "minAge": 8,
  "maxAge": 10,
  "ageGroup": "5to12",
  "image": "132-marble-tracks-builder-set.jpg"
},
{
  "id": 133,
  "name": "Math Dice",
  "description": "Math game.",
  "categoryId": "toys",
  "cost": 11,
  "price": 11,
  "ageRange": "9-16",
  "minAge": 9,
  "maxAge": 16,
  "ageGroup": "12plus",
  "image": "133-math-dice.jpg"
},
{
  "id": 134,
  "name": "Mega Blocks",
  "description": "80 blocks",
  "categoryId": "toys",
  "cost": 24,
  "price": 24,
  "ageRange": "1-3",
  "minAge": 1,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "134-mega-blocks.jpg"
},
{
  "id": 135,
  "name": "Mr. Potato Head",
  "description": "Classic!",
  "categoryId": "toys",
  "cost": 8,
  "price": 8,
  "ageRange": "3-8",
  "minAge": 3,
  "maxAge": 8,
  "ageGroup": "5to12",
  "image": "135-mr-potato-head.jpg"
},
{
  "id": 136,
  "name": "Musical Toy",
  "description": "Sensory Learning Music",
  "categoryId": "toys",
  "cost": 7,
  "price": 7,
  "ageRange": "1-3",
  "minAge": 1,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "136-musical-toy.jpg"
},
{
  "id": 137,
  "name": "Music Parade Ride-On",
  "description": "Cool ride and musical fun!",
  "categoryId": "toys",
  "cost": 50,
  "price": 50,
  "ageRange": "1-2",
  "minAge": 1,
  "maxAge": 2,
  "ageGroup": "under5",
  "image": "137-music-parade-ride-on.png"
},
{
  "id": 138,
  "name": "My Toolbox",
  "description": "Describes how a house is built.",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "1-5",
  "minAge": 1,
  "maxAge": 5,
  "ageGroup": "under5",
  "image": "138-my-toolbox.jpg"
},
{
  "id": 139,
  "name": "Picnic Set",
  "description": "Stimulate Picnic Experience with toys",
  "categoryId": "toys",
  "cost": 22,
  "price": 22,
  "ageRange": "3-6",
  "minAge": 3,
  "maxAge": 6,
  "ageGroup": "under5",
  "image": "139-picnic-set.jpg"
},
{
  "id": 140,
  "name": "Play Tunnel",
  "description": "Colorful!",
  "categoryId": "toys",
  "cost": 20,
  "price": 20,
  "ageRange": "3-6",
  "minAge": 3,
  "maxAge": 6,
  "ageGroup": "under5",
  "image": "140-play-tunnel.jpg"
},
{
  "id": 141,
  "name": "Pop-its 100",
  "description": "Fidget with numbers up to 100",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "4-10",
  "minAge": 4,
  "maxAge": 10,
  "ageGroup": "5to12",
  "image": "141-pop-its-100.jpg"
},
{
  "id": 142,
  "name": "Pop its 1-100",
  "description": "Fidget with numbers up to 100",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "4-10",
  "minAge": 4,
  "maxAge": 10,
  "ageGroup": "5to12",
  "image": "142-pop-its-1-100.jpg"
},
{
  "id": 143,
  "name": "Pop-Its Fidgets",
  "description": "Colors vary.",
  "categoryId": "toys",
  "cost": 3,
  "price": 3,
  "ageRange": "4-10",
  "minAge": 4,
  "maxAge": 10,
  "ageGroup": "5to12",
  "image": "143-pop-its-fidgets.jpg"
},
{
  "id": 144,
  "name": "Pound-A-Ball Toy",
  "description": "Wooden 4-wheel car, pound a ball, and shape sorter.",
  "categoryId": "toys",
  "cost": 23,
  "price": 23,
  "ageRange": "2-3",
  "minAge": 2,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "144-pound-a-ball-toy.jpg"
},
{
  "id": 145,
  "name": "Princess Tent",
  "description": "Indoor and outdoor. Star Lights included. 55'' x 53''",
  "categoryId": "toys",
  "cost": 37,
  "price": 37,
  "ageRange": "4-7",
  "minAge": 4,
  "maxAge": 7,
  "ageGroup": "5to12",
  "image": "145-princess-tent.png"
},
{
  "id": 146,
  "name": "Ring Spinners",
  "description": "Magnetic Fidget",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "9-18",
  "minAge": 9,
  "maxAge": 18,
  "ageGroup": "12plus",
  "image": "146-ring-spinners.jpg"
},
{
  "id": 147,
  "name": "Rock n Roller Piano",
  "description": "Melody-making fun!",
  "categoryId": "toys",
  "cost": 30,
  "price": 30,
  "ageRange": "1-2",
  "minAge": 1,
  "maxAge": 2,
  "ageGroup": "under5",
  "image": "147-rock-n-roller-piano.webp"
},
{
  "id": 148,
  "name": "Rocking Horse",
  "description": "Learn balance and coordination.",
  "categoryId": "toys",
  "cost": 35,
  "price": 35,
  "ageRange": "1-3",
  "minAge": 1,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "148-rocking-horse.jpg"
},
{
  "id": 149,
  "name": "Rubber Ball",
  "description": "9-inch rubber kickball.",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "2-10",
  "minAge": 2,
  "maxAge": 10,
  "ageGroup": "5to12",
  "image": "149-rubber-ball.jpg"
},
{
  "id": 150,
  "name": "Rubber Pop Up Toys",
  "description": "Flips inside out and back.",
  "categoryId": "toys",
  "cost": 12,
  "price": 12,
  "ageRange": "3-7",
  "minAge": 3,
  "maxAge": 7,
  "ageGroup": "5to12",
  "image": "150-rubber-pop-up-toys.jpg"
},

    {
  "id": 151,
  "name": "Rubiks Cube",
  "description": "Classic solve the cube",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "8-15",
  "minAge": 8,
  "maxAge": 15,
  "ageGroup": "5to12",
  "image": "151-rubiks-cube.jpg"
},
{
  "id": 152,
  "name": "Sensory Strings - 6 pack",
  "description": "6 pack. Stress relief. Visual stimulation.",
  "categoryId": "toys",
  "cost": 12,
  "price": 12,
  "ageRange": "6-18",
  "minAge": 6,
  "maxAge": 18,
  "ageGroup": "5to12",
  "image": "152-sensory-strings-6-pack.jpg"
},
{
  "id": 153,
  "name": "Sit n Spin",
  "description": "Sit, spin, and giggle yourself silly.",
  "categoryId": "toys",
  "cost": 35,
  "price": 35,
  "ageRange": "2-5",
  "minAge": 2,
  "maxAge": 5,
  "ageGroup": "under5",
  "image": "153-sit-n-spin.png"
},
{
  "id": 154,
  "name": "Slide for Toddlers",
  "description": "Safe for younger kids. Indoor and outdoors use.",
  "categoryId": "toys",
  "cost": 25,
  "price": 25,
  "ageRange": "2-3",
  "minAge": 2,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "154-slide-for-toddlers.jpg"
},
{
  "id": 155,
  "name": "Slinky",
  "description": "Classic spring walking toy.",
  "categoryId": "toys",
  "cost": 4,
  "price": 4,
  "ageRange": "5-18",
  "minAge": 5,
  "maxAge": 18,
  "ageGroup": "5to12",
  "image": "155-slinky.jpg"
},
{
  "id": 156,
  "name": "Snow Beauty",
  "description": "Frozen Theme Tea Set",
  "categoryId": "toys",
  "cost": 28,
  "price": 28,
  "ageRange": "3-6",
  "minAge": 3,
  "maxAge": 6,
  "ageGroup": "under5",
  "image": "156-snow-beauty.jpg"
},
{
  "id": 157,
  "name": "Spa Kit",
  "description": "Inflatable tub DIY Manicure/Pedicure",
  "categoryId": "toys",
  "cost": 25,
  "price": 25,
  "ageRange": "6-9",
  "minAge": 6,
  "maxAge": 9,
  "ageGroup": "5to12",
  "image": "157-spa-kit.jpg"
},
{
  "id": 158,
  "name": "Spike the Hedgehog",
  "description": "Fine motor and sensory learning.",
  "categoryId": "toys",
  "cost": 14,
  "price": 14,
  "ageRange": "2-4",
  "minAge": 2,
  "maxAge": 4,
  "ageGroup": "under5",
  "image": "158-spike-the-hedgehog.jpg"
},
{
  "id": 159,
  "name": "Stack and Count Cups",
  "description": "8 cups",
  "categoryId": "toys",
  "cost": 8,
  "price": 8,
  "ageRange": "1-3",
  "minAge": 1,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "159-stack-and-count-cups.jpg"
},
{
  "id": 160,
  "name": "Stuffed Animal - Dog",
  "description": "10' plush",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "1-18",
  "minAge": 1,
  "maxAge": 18,
  "ageGroup": "5to12",
  "image": "160-stuffed-animal-dog.jpg"
},
{
  "id": 161,
  "name": "Stuffed Animal - Hamburger Bear",
  "description": "Happy Birthday!",
  "categoryId": "toys",
  "cost": 11,
  "price": 11,
  "ageRange": "1-18",
  "minAge": 1,
  "maxAge": 18,
  "ageGroup": "5to12",
  "image": "161-stuffed-animal-hamburger-bear.jpg"
},
{
  "id": 162,
  "name": "Stuffed Animal - Hedgehog",
  "description": "10\" plush",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "1-18",
  "minAge": 1,
  "maxAge": 18,
  "ageGroup": "5to12",
  "image": "162-stuffed-animal-hedgehog.jpg"
},
{
  "id": 163,
  "name": "Stuffed Animal - Unicorn Cat",
  "description": "Happy Birthday!",
  "categoryId": "toys",
  "cost": 12,
  "price": 12,
  "ageRange": "1-18",
  "minAge": 1,
  "maxAge": 18,
  "ageGroup": "5to12",
  "image": "163-stuffed-animal-unicorn-cat.jpg"
},
{
  "id": 164,
  "name": "Super Heroes - Action Figures",
  "description": "5 Super Hero Action Heroes",
  "categoryId": "toys",
  "cost": 12,
  "price": 12,
  "ageRange": "5-14",
  "minAge": 5,
  "maxAge": 14,
  "ageGroup": "5to12",
  "image": "164-super-heroes-action-figures.jpg"
},
{
  "id": 165,
  "name": "Tea Party Set",
  "description": "With Play food",
  "categoryId": "toys",
  "cost": 15,
  "price": 15,
  "ageRange": "3-6",
  "minAge": 3,
  "maxAge": 6,
  "ageGroup": "under5",
  "image": "165-tea-party-set.jpg"
},
{
  "id": 166,
  "name": "Thinking Putty - Mixed Emotions",
  "description": "Emojis Stretchy putty",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "3-18",
  "minAge": 3,
  "maxAge": 18,
  "ageGroup": "5to12",
  "image": "166-thinking-putty-mixed-emotions.png"
},
{
  "id": 167,
  "name": "Toddler Bike",
  "description": "Colorful wooden bike!",
  "categoryId": "toys",
  "cost": 40,
  "price": 40,
  "ageRange": "1-3",
  "minAge": 1,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "167-toddler-bike.webp"
},
{
  "id": 168,
  "name": "Transformable Spinner",
  "description": "Fidget Spinners",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "8-18",
  "minAge": 8,
  "maxAge": 18,
  "ageGroup": "12plus",
  "image": "168-transformable-spinner.jpg"
},
{
  "id": 169,
  "name": "Unicorn Tea Set",
  "description": "Tea Set Magical Unicorns, Rainbows and Stars",
  "categoryId": "toys",
  "cost": 28,
  "price": 28,
  "ageRange": "3-8",
  "minAge": 3,
  "maxAge": 8,
  "ageGroup": "5to12",
  "image": "169-unicorn-tea-set.jpg"
},

{
  "id": 173,
  "name": "Wood Blocks",
  "description": "50 block set.",
  "categoryId": "toys",
  "cost": 22,
  "price": 22,
  "ageRange": "2-3",
  "minAge": 2,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "173-wood-blocks.jpg"
},
{
  "id": 174,
  "name": "Wooden Bee Ride-on",
  "description": "Made with natural wood.",
  "categoryId": "toys",
  "cost": 32,
  "price": 32,
  "ageRange": "1-4",
  "minAge": 1,
  "maxAge": 4,
  "ageGroup": "under5",
  "image": "174-wooden-bee-ride-on.jpg"
},
{
  "id": 175,
  "name": "Wooden Stacking Rings",
  "description": "Rainbow colors.",
  "categoryId": "toys",
  "cost": 11,
  "price": 11,
  "ageRange": "9-18",
  "minAge": 9,
  "maxAge": 18,
  "ageGroup": "12plus",
  "image": "175-wooden-stacking-rings.jpg"
},
    {
  "id": 176,
  "name": "Yo yo",
  "description": "Colors vary.",
  "categoryId": "toys",
  "cost": 5,
  "price": 5,
  "ageRange": "1-5",
  "minAge": 1,
  "maxAge": 5,
  "ageGroup": "under5",
  "image": "176-yo-yo.jpg"
},
{
  "id": 177,
  "name": "Black Boy Doll",
  "description": "14\" dark skin tone.",
  "categoryId": "toys",
  "cost": 17,
  "price": 17,
  "ageRange": "1-8",
  "minAge": 1,
  "maxAge": 8,
  "ageGroup": "under5",
  "image": "177-black-boy-doll.webp"
},
{
  "id": 178,
  "name": "Boy Doll",
  "description": "14\" plush doll",
  "categoryId": "toys",
  "cost": 17,
  "price": 17,
  "ageRange": "1-8",
  "minAge": 1,
  "maxAge": 8,
  "ageGroup": "under5",
  "image": "178-boy-doll.jpg"
},
{
  "id": 179,
  "name": "Doll Girl",
  "description": "14\" plush doll.",
  "categoryId": "toys",
  "cost": 17,
  "price": 17,
  "ageRange": "1-5",
  "minAge": 1,
  "maxAge": 5,
  "ageGroup": "under5",
  "image": "179-doll-girl.jpg"
},
{
  "id": 180,
  "name": "Girl Plush Doll",
  "description": "14\" plush doll",
  "categoryId": "toys",
  "cost": 20,
  "price": 20,
  "ageRange": "3-5",
  "minAge": 3,
  "maxAge": 5,
  "ageGroup": "under5",
  "image": "180-girl-plush-doll.jpg"
},
{
  "id": 181,
  "name": "La Baby Hispanic Doll",
  "description": "La Baby 20\". Huggable and easy to cuddle.",
  "categoryId": "toys",
  "cost": 30,
  "price": 30,
  "ageRange": "1-3",
  "minAge": 1,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "181-la-baby-hispanic-doll.png"
},
{
  "id": 182,
  "name": "Latino Baby Doll",
  "description": "10\" soft",
  "categoryId": "toys",
  "cost": 15,
  "price": 15,
  "ageRange": "4-8",
  "minAge": 4,
  "maxAge": 8,
  "ageGroup": "5to12",
  "image": "182-latino-baby-doll.jpg"
},
{
  "id": 183,
  "name": "Soccer Doll",
  "description": "Ken Fashion Doll & Accessory, Soccer Player",
  "categoryId": "toys",
  "cost": 12,
  "price": 12,
  "ageRange": "1-3",
  "minAge": 1,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "183-soccer-doll.jpg"
},
{
  "id": 184,
  "name": "Wee Baby Doll",
  "description": "Wee Baby Stella Brown 12\" Soft Baby Doll.",
  "categoryId": "toys",
  "cost": 26,
  "price": 26,
  "ageRange": "1-6",
  "minAge": 1,
  "maxAge": 6,
  "ageGroup": "under5",
  "image": "184-wee-baby-doll.jpeg"
},
{
  "id": 185,
  "name": "White Baby Doll",
  "description": "8\" plush",
  "categoryId": "toys",
  "cost": 15,
  "price": 15,
  "ageRange": "4-12",
  "minAge": 4,
  "maxAge": 12,
  "ageGroup": "5to12",
  "image": "185-white-baby-doll.jpg"
},
{
  "id": 186,
  "name": "Wildlife Photographer Doll",
  "description": "Mia - 7\" doll Photography accessories.",
  "categoryId": "toys",
  "cost": 28,
  "price": 28,
  "ageRange": "2-4",
  "minAge": 2,
  "maxAge": 4,
  "ageGroup": "under5",
  "image": "186-wildlife-photographer-doll.webp"
},
{
  "id": 187,
  "name": "Doll Red Dress",
  "description": "14\" soft sensory fabric",
  "categoryId": "toys",
  "cost": 14,
  "price": 14,
  "ageRange": "8-18",
  "minAge": 8,
  "maxAge": 18,
  "ageGroup": "12plus",
  "image": "187-doll-red-dress.jpg"
},
{
  "id": 188,
  "name": "Legos Chain Reaction",
  "description": "10 moving machines.",
  "categoryId": "toys",
  "cost": 22,
  "price": 22,
  "ageRange": "7-12",
  "minAge": 7,
  "maxAge": 12,
  "ageGroup": "5to12",
  "image": "188-legos-chain-reaction.jpg"
},
{
  "id": 189,
  "name": "Legos Dino",
  "description": "3 in 1 Dinosaur Lego Set",
  "categoryId": "toys",
  "cost": 15,
  "price": 15,
  "ageRange": "13-18",
  "minAge": 13,
  "maxAge": 18,
  "ageGroup": "12plus",
  "image": "189-legos-dino.jpg"
},
{
  "id": 190,
  "name": "Legos Flower",
  "description": "LEGO Plum Blossoms",
  "categoryId": "toys",
  "cost": 24,
  "price": 24,
  "ageRange": "0-3",
  "minAge": 0,
  "maxAge": 3,
  "ageGroup": "under5",
  "image": "190-legos-flower.jpg"
},
{
  "id": 191,
  "name": "Legos Gearbots",
  "description": "LEGO kit - 8 different moving machines.",
  "categoryId": "toys",
  "cost": 25,
  "price": 25,
  "ageRange": "7-12",
  "minAge": 7,
  "maxAge": 12,
  "ageGroup": "5to12",
  "image": "191-legos-gearbots.jpg"
},
{
  "id": 192,
  "name": "Lego Set",
  "description": "Deep Sea Creatures.",
  "categoryId": "toys",
  "cost": 15,
  "price": 15,
  "ageRange": "8-18",
  "minAge": 8,
  "maxAge": 18,
  "ageGroup": "12plus",
  "image": "192-lego-set.jpg"
},
{
  "id": 193,
  "name": "Lego Spiderman",
  "description": "LEGO Spider-Man Action Figure",
  "categoryId": "toys",
  "cost": 20,
  "price": 20,
  "ageRange": "3-6",
  "minAge": 3,
  "maxAge": 6,
  "ageGroup": "under5",
  "image": "193-lego-spiderman.jpg"
},
{
  "id": 194,
  "name": "Construction Trucks",
  "description": "Set of 4",
  "categoryId": "toys",
  "cost": 17,
  "price": 17,
  "ageRange": "3-6",
  "minAge": 3,
  "maxAge": 6,
  "ageGroup": "under5",
  "image": "194-construction-trucks.jpg"
},
{
  "id": 195,
  "name": "Emergency Vehicle Carrier",
  "description": "Truck and emergency vehicle toy set.",
  "categoryId": "toys",
  "cost": 16,
  "price": 16,
  "ageRange": "6-9",
  "minAge": 6,
  "maxAge": 9,
  "ageGroup": "5to12",
  "image": "195-emergency-vehicle-carrier.jpg"
},
{
  "id": 196,
  "name": "Hot Wheels Track Builder",
  "description": "Gas-can-shaped container holds track pieces + 1 Hot Wheels Car.",
  "categoryId": "toys",
  "cost": 28,
  "price": 28,
  "ageRange": "3-5",
  "minAge": 3,
  "maxAge": 5,
  "ageGroup": "under5",
  "image": "196-hot-wheels-track-builder.jpg"
},
{
  "id": 197,
  "name": "John Deere Trucks",
  "description": "Tractor and dump truck toy.",
  "categoryId": "toys",
  "cost": 10,
  "price": 10,
  "ageRange": "6-8",
  "minAge": 6,
  "maxAge": 8,
  "ageGroup": "5to12",
  "image": "197-john-deere-trucks.jpg"
},
{
  "id": 198,
  "name": "Magnetic Racer",
  "description": "Magnetic force power.",
  "categoryId": "toys",
  "cost": 7,
  "price": 7,
  "ageRange": "3-7",
  "minAge": 3,
  "maxAge": 7,
  "ageGroup": "5to12",
  "image": "198-magnetic-racer.png"
},
{
  "id": 199,
  "name": "Monster Trucks",
  "description": "Set of 4",
  "categoryId": "toys",
  "cost": 15,
  "price": 15,
  "ageRange": "2-5",
  "minAge": 2,
  "maxAge": 5,
  "ageGroup": "under5",
  "image": "199-monster-trucks.jpg"
},
{
  "id": 200,
  "name": "Neighbor's Garage",
  "description": "Garage play set. 2 cars included.",
  "categoryId": "toys",
  "cost": 16,
  "price": 16,
  "ageRange": "2-5",
  "minAge": 2,
  "maxAge": 5,
  "ageGroup": "under5",
  "image": "200-neighbor-s-garage.jpg"
}
],
};
